// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GenshinGateway.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hi3Helper.EncTool.Proto.Genshin {

  /// <summary>Holder for reflection information generated from GenshinGateway.proto</summary>
  public static partial class GenshinGatewayReflection {

    #region Descriptor
    /// <summary>File descriptor for GenshinGateway.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenshinGatewayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRHZW5zaGluR2F0ZXdheS5wcm90bxIfSGkzSGVscGVyLkVuY1Rvb2wuUHJv",
            "dG8uR2Vuc2hpbiLnBwoOR2Vuc2hpbkdhdGV3YXkSVQoRR2F0ZXdheVByb3Bl",
            "cnRpZXMYAyABKAsyOi5IaTNIZWxwZXIuRW5jVG9vbC5Qcm90by5HZW5zaGlu",
            "LkdlbnNoaW5HYXRld2F5LlByb3BlcnRpZXMSGwoTU2VydmVyUHJvdG9Qcml2",
            "S2V5MRgLIAEoDBIbChNTZXJ2ZXJQcm90b1ByaXZLZXkyGAwgASgMGsMGCgpQ",
            "cm9wZXJ0aWVzEhIKClNlcnZlck5hbWUYByABKAkSEwoLU2VydmVyT0FVUkwY",
            "AyABKAkSHgoWU2VydmVyU2VydmljZUNlbnRlclVSTBgKIAEoCRIWCg5TZXJ2",
            "ZXJMb2dpblVSTBgfIAEoCRIWCg5TZXJ2ZXJDREtleVVSTBggIAEoCRIaChJT",
            "ZXJ2ZXJBZ3JlZW1lbnRVUkwYISABKAkSFQoNU2VydmVyUHJvdG9JUBgBIAEo",
            "CRIXCg9TZXJ2ZXJQcm90b1BvcnQYAiABKA0SGgoSU2VydmVyUHJvdG9WZXJz",
            "aW9uGAwgASgJEhkKEVNlcnZlclByb3RvUHViS2V5GBcgASgMEhkKEVJlcG9S",
            "ZXNWZXJzaW9uVVJMGAggASgJEmcKGFJlcG9SZXNWZXJzaW9uUHJvcGVydGll",
            "cxgWIAEoCzJFLkhpM0hlbHBlci5FbmNUb29sLlByb3RvLkdlbnNoaW4uR2Vu",
            "c2hpbkdhdGV3YXkuUHJvcGVydGllcy5SZXNWZXJzaW9uEhkKEVJlcG9EZXNp",
            "Z25EYXRhVVJMGAkgASgJEhwKFFJlcG9EZXNpZ25EYXRhTnVtYmVyGA4gASgN",
            "EhoKElJlcG9EZXNpZ25EYXRhSlNPThgTIAEoCRIaChJSZXBvRGVzaWduRGF0",
            "YUhhc2gYGiABKAkSIwobUmVwb0Rlc2lnbkRhdGFTaWxlbmNlTnVtYmVyGBIg",
            "ASgNEiEKGVJlcG9EZXNpZ25EYXRhU2lsZW5jZUpTT04YFCABKAkSIQoZUmVw",
            "b0Rlc2lnbkRhdGFTaWxlbmNlSGFzaBgbIAEoCRIeChZFdmVudFZlcnNpb25Q",
            "cmV2aWV3VVJMGBAgASgJEhUKDUV2ZW50RnJvbnRVUkwYGCABKAkSFAoMR2Ft",
            "ZUNvZGVuYW1lGCQgASgJGosBCgpSZXNWZXJzaW9uEhgKEFJlc1ZlcnNpb25O",
            "dW1iZXIYASABKA0SGQoRUmVzVmVyc2lvbk1hcEpTT04YAyABKAkSHAoUUmVz",
            "VmVyc2lvbk1pblZlcnNpb24YBCABKAkSFgoOUmVzVmVyc2lvbkhhc2gYBSAB",
            "KAkSEgoKUmVzVmVyc2lvbhgGIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway), global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Parser, new[]{ "GatewayProperties", "ServerProtoPrivKey1", "ServerProtoPrivKey2" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties), global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Parser, new[]{ "ServerName", "ServerOAURL", "ServerServiceCenterURL", "ServerLoginURL", "ServerCDKeyURL", "ServerAgreementURL", "ServerProtoIP", "ServerProtoPort", "ServerProtoVersion", "ServerProtoPubKey", "RepoResVersionURL", "RepoResVersionProperties", "RepoDesignDataURL", "RepoDesignDataNumber", "RepoDesignDataJSON", "RepoDesignDataHash", "RepoDesignDataSilenceNumber", "RepoDesignDataSilenceJSON", "RepoDesignDataSilenceHash", "EventVersionPreviewURL", "EventFrontURL", "GameCodename" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion), global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion.Parser, new[]{ "ResVersionNumber", "ResVersionMapJSON", "ResVersionMinVersion", "ResVersionHash", "ResVersion_" }, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GenshinGateway : pb::IMessage<GenshinGateway>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenshinGateway> _parser = new pb::MessageParser<GenshinGateway>(() => new GenshinGateway());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenshinGateway> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.EncTool.Proto.Genshin.GenshinGatewayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenshinGateway() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenshinGateway(GenshinGateway other) : this() {
      gatewayProperties_ = other.gatewayProperties_ != null ? other.gatewayProperties_.Clone() : null;
      serverProtoPrivKey1_ = other.serverProtoPrivKey1_;
      serverProtoPrivKey2_ = other.serverProtoPrivKey2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenshinGateway Clone() {
      return new GenshinGateway(this);
    }

    /// <summary>Field number for the "GatewayProperties" field.</summary>
    public const int GatewayPropertiesFieldNumber = 3;
    private global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties gatewayProperties_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties GatewayProperties {
      get { return gatewayProperties_; }
      set {
        gatewayProperties_ = value;
      }
    }

    /// <summary>Field number for the "ServerProtoPrivKey1" field.</summary>
    public const int ServerProtoPrivKey1FieldNumber = 11;
    private pb::ByteString serverProtoPrivKey1_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ServerProtoPrivKey1 {
      get { return serverProtoPrivKey1_; }
      set {
        serverProtoPrivKey1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerProtoPrivKey2" field.</summary>
    public const int ServerProtoPrivKey2FieldNumber = 12;
    private pb::ByteString serverProtoPrivKey2_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ServerProtoPrivKey2 {
      get { return serverProtoPrivKey2_; }
      set {
        serverProtoPrivKey2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenshinGateway);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenshinGateway other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GatewayProperties, other.GatewayProperties)) return false;
      if (ServerProtoPrivKey1 != other.ServerProtoPrivKey1) return false;
      if (ServerProtoPrivKey2 != other.ServerProtoPrivKey2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (gatewayProperties_ != null) hash ^= GatewayProperties.GetHashCode();
      if (ServerProtoPrivKey1.Length != 0) hash ^= ServerProtoPrivKey1.GetHashCode();
      if (ServerProtoPrivKey2.Length != 0) hash ^= ServerProtoPrivKey2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (gatewayProperties_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GatewayProperties);
      }
      if (ServerProtoPrivKey1.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(ServerProtoPrivKey1);
      }
      if (ServerProtoPrivKey2.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(ServerProtoPrivKey2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (gatewayProperties_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GatewayProperties);
      }
      if (ServerProtoPrivKey1.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(ServerProtoPrivKey1);
      }
      if (ServerProtoPrivKey2.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(ServerProtoPrivKey2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (gatewayProperties_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GatewayProperties);
      }
      if (ServerProtoPrivKey1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ServerProtoPrivKey1);
      }
      if (ServerProtoPrivKey2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ServerProtoPrivKey2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenshinGateway other) {
      if (other == null) {
        return;
      }
      if (other.gatewayProperties_ != null) {
        if (gatewayProperties_ == null) {
          GatewayProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties();
        }
        GatewayProperties.MergeFrom(other.GatewayProperties);
      }
      if (other.ServerProtoPrivKey1.Length != 0) {
        ServerProtoPrivKey1 = other.ServerProtoPrivKey1;
      }
      if (other.ServerProtoPrivKey2.Length != 0) {
        ServerProtoPrivKey2 = other.ServerProtoPrivKey2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (gatewayProperties_ == null) {
              GatewayProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties();
            }
            input.ReadMessage(GatewayProperties);
            break;
          }
          case 90: {
            ServerProtoPrivKey1 = input.ReadBytes();
            break;
          }
          case 98: {
            ServerProtoPrivKey2 = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            if (gatewayProperties_ == null) {
              GatewayProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties();
            }
            input.ReadMessage(GatewayProperties);
            break;
          }
          case 90: {
            ServerProtoPrivKey1 = input.ReadBytes();
            break;
          }
          case 98: {
            ServerProtoPrivKey2 = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GenshinGateway message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Properties : pb::IMessage<Properties>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Properties> _parser = new pb::MessageParser<Properties>(() => new Properties());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Properties> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Properties() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Properties(Properties other) : this() {
          serverName_ = other.serverName_;
          serverOAURL_ = other.serverOAURL_;
          serverServiceCenterURL_ = other.serverServiceCenterURL_;
          serverLoginURL_ = other.serverLoginURL_;
          serverCDKeyURL_ = other.serverCDKeyURL_;
          serverAgreementURL_ = other.serverAgreementURL_;
          serverProtoIP_ = other.serverProtoIP_;
          serverProtoPort_ = other.serverProtoPort_;
          serverProtoVersion_ = other.serverProtoVersion_;
          serverProtoPubKey_ = other.serverProtoPubKey_;
          repoResVersionURL_ = other.repoResVersionURL_;
          repoResVersionProperties_ = other.repoResVersionProperties_ != null ? other.repoResVersionProperties_.Clone() : null;
          repoDesignDataURL_ = other.repoDesignDataURL_;
          repoDesignDataNumber_ = other.repoDesignDataNumber_;
          repoDesignDataJSON_ = other.repoDesignDataJSON_;
          repoDesignDataHash_ = other.repoDesignDataHash_;
          repoDesignDataSilenceNumber_ = other.repoDesignDataSilenceNumber_;
          repoDesignDataSilenceJSON_ = other.repoDesignDataSilenceJSON_;
          repoDesignDataSilenceHash_ = other.repoDesignDataSilenceHash_;
          eventVersionPreviewURL_ = other.eventVersionPreviewURL_;
          eventFrontURL_ = other.eventFrontURL_;
          gameCodename_ = other.gameCodename_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Properties Clone() {
          return new Properties(this);
        }

        /// <summary>Field number for the "ServerName" field.</summary>
        public const int ServerNameFieldNumber = 7;
        private string serverName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerName {
          get { return serverName_; }
          set {
            serverName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerOAURL" field.</summary>
        public const int ServerOAURLFieldNumber = 3;
        private string serverOAURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerOAURL {
          get { return serverOAURL_; }
          set {
            serverOAURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerServiceCenterURL" field.</summary>
        public const int ServerServiceCenterURLFieldNumber = 10;
        private string serverServiceCenterURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerServiceCenterURL {
          get { return serverServiceCenterURL_; }
          set {
            serverServiceCenterURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerLoginURL" field.</summary>
        public const int ServerLoginURLFieldNumber = 31;
        private string serverLoginURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerLoginURL {
          get { return serverLoginURL_; }
          set {
            serverLoginURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerCDKeyURL" field.</summary>
        public const int ServerCDKeyURLFieldNumber = 32;
        private string serverCDKeyURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerCDKeyURL {
          get { return serverCDKeyURL_; }
          set {
            serverCDKeyURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerAgreementURL" field.</summary>
        public const int ServerAgreementURLFieldNumber = 33;
        private string serverAgreementURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerAgreementURL {
          get { return serverAgreementURL_; }
          set {
            serverAgreementURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerProtoIP" field.</summary>
        public const int ServerProtoIPFieldNumber = 1;
        private string serverProtoIP_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerProtoIP {
          get { return serverProtoIP_; }
          set {
            serverProtoIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerProtoPort" field.</summary>
        public const int ServerProtoPortFieldNumber = 2;
        private uint serverProtoPort_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ServerProtoPort {
          get { return serverProtoPort_; }
          set {
            serverProtoPort_ = value;
          }
        }

        /// <summary>Field number for the "ServerProtoVersion" field.</summary>
        public const int ServerProtoVersionFieldNumber = 12;
        private string serverProtoVersion_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServerProtoVersion {
          get { return serverProtoVersion_; }
          set {
            serverProtoVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ServerProtoPubKey" field.</summary>
        public const int ServerProtoPubKeyFieldNumber = 23;
        private pb::ByteString serverProtoPubKey_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString ServerProtoPubKey {
          get { return serverProtoPubKey_; }
          set {
            serverProtoPubKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoResVersionURL" field.</summary>
        public const int RepoResVersionURLFieldNumber = 8;
        private string repoResVersionURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoResVersionURL {
          get { return repoResVersionURL_; }
          set {
            repoResVersionURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoResVersionProperties" field.</summary>
        public const int RepoResVersionPropertiesFieldNumber = 22;
        private global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion repoResVersionProperties_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion RepoResVersionProperties {
          get { return repoResVersionProperties_; }
          set {
            repoResVersionProperties_ = value;
          }
        }

        /// <summary>Field number for the "RepoDesignDataURL" field.</summary>
        public const int RepoDesignDataURLFieldNumber = 9;
        private string repoDesignDataURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoDesignDataURL {
          get { return repoDesignDataURL_; }
          set {
            repoDesignDataURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoDesignDataNumber" field.</summary>
        public const int RepoDesignDataNumberFieldNumber = 14;
        private uint repoDesignDataNumber_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RepoDesignDataNumber {
          get { return repoDesignDataNumber_; }
          set {
            repoDesignDataNumber_ = value;
          }
        }

        /// <summary>Field number for the "RepoDesignDataJSON" field.</summary>
        public const int RepoDesignDataJSONFieldNumber = 19;
        private string repoDesignDataJSON_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoDesignDataJSON {
          get { return repoDesignDataJSON_; }
          set {
            repoDesignDataJSON_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoDesignDataHash" field.</summary>
        public const int RepoDesignDataHashFieldNumber = 26;
        private string repoDesignDataHash_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoDesignDataHash {
          get { return repoDesignDataHash_; }
          set {
            repoDesignDataHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoDesignDataSilenceNumber" field.</summary>
        public const int RepoDesignDataSilenceNumberFieldNumber = 18;
        private uint repoDesignDataSilenceNumber_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RepoDesignDataSilenceNumber {
          get { return repoDesignDataSilenceNumber_; }
          set {
            repoDesignDataSilenceNumber_ = value;
          }
        }

        /// <summary>Field number for the "RepoDesignDataSilenceJSON" field.</summary>
        public const int RepoDesignDataSilenceJSONFieldNumber = 20;
        private string repoDesignDataSilenceJSON_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoDesignDataSilenceJSON {
          get { return repoDesignDataSilenceJSON_; }
          set {
            repoDesignDataSilenceJSON_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "RepoDesignDataSilenceHash" field.</summary>
        public const int RepoDesignDataSilenceHashFieldNumber = 27;
        private string repoDesignDataSilenceHash_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RepoDesignDataSilenceHash {
          get { return repoDesignDataSilenceHash_; }
          set {
            repoDesignDataSilenceHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "EventVersionPreviewURL" field.</summary>
        public const int EventVersionPreviewURLFieldNumber = 16;
        private string eventVersionPreviewURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string EventVersionPreviewURL {
          get { return eventVersionPreviewURL_; }
          set {
            eventVersionPreviewURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "EventFrontURL" field.</summary>
        public const int EventFrontURLFieldNumber = 24;
        private string eventFrontURL_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string EventFrontURL {
          get { return eventFrontURL_; }
          set {
            eventFrontURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "GameCodename" field.</summary>
        public const int GameCodenameFieldNumber = 36;
        private string gameCodename_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string GameCodename {
          get { return gameCodename_; }
          set {
            gameCodename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Properties);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Properties other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ServerName != other.ServerName) return false;
          if (ServerOAURL != other.ServerOAURL) return false;
          if (ServerServiceCenterURL != other.ServerServiceCenterURL) return false;
          if (ServerLoginURL != other.ServerLoginURL) return false;
          if (ServerCDKeyURL != other.ServerCDKeyURL) return false;
          if (ServerAgreementURL != other.ServerAgreementURL) return false;
          if (ServerProtoIP != other.ServerProtoIP) return false;
          if (ServerProtoPort != other.ServerProtoPort) return false;
          if (ServerProtoVersion != other.ServerProtoVersion) return false;
          if (ServerProtoPubKey != other.ServerProtoPubKey) return false;
          if (RepoResVersionURL != other.RepoResVersionURL) return false;
          if (!object.Equals(RepoResVersionProperties, other.RepoResVersionProperties)) return false;
          if (RepoDesignDataURL != other.RepoDesignDataURL) return false;
          if (RepoDesignDataNumber != other.RepoDesignDataNumber) return false;
          if (RepoDesignDataJSON != other.RepoDesignDataJSON) return false;
          if (RepoDesignDataHash != other.RepoDesignDataHash) return false;
          if (RepoDesignDataSilenceNumber != other.RepoDesignDataSilenceNumber) return false;
          if (RepoDesignDataSilenceJSON != other.RepoDesignDataSilenceJSON) return false;
          if (RepoDesignDataSilenceHash != other.RepoDesignDataSilenceHash) return false;
          if (EventVersionPreviewURL != other.EventVersionPreviewURL) return false;
          if (EventFrontURL != other.EventFrontURL) return false;
          if (GameCodename != other.GameCodename) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ServerName.Length != 0) hash ^= ServerName.GetHashCode();
          if (ServerOAURL.Length != 0) hash ^= ServerOAURL.GetHashCode();
          if (ServerServiceCenterURL.Length != 0) hash ^= ServerServiceCenterURL.GetHashCode();
          if (ServerLoginURL.Length != 0) hash ^= ServerLoginURL.GetHashCode();
          if (ServerCDKeyURL.Length != 0) hash ^= ServerCDKeyURL.GetHashCode();
          if (ServerAgreementURL.Length != 0) hash ^= ServerAgreementURL.GetHashCode();
          if (ServerProtoIP.Length != 0) hash ^= ServerProtoIP.GetHashCode();
          if (ServerProtoPort != 0) hash ^= ServerProtoPort.GetHashCode();
          if (ServerProtoVersion.Length != 0) hash ^= ServerProtoVersion.GetHashCode();
          if (ServerProtoPubKey.Length != 0) hash ^= ServerProtoPubKey.GetHashCode();
          if (RepoResVersionURL.Length != 0) hash ^= RepoResVersionURL.GetHashCode();
          if (repoResVersionProperties_ != null) hash ^= RepoResVersionProperties.GetHashCode();
          if (RepoDesignDataURL.Length != 0) hash ^= RepoDesignDataURL.GetHashCode();
          if (RepoDesignDataNumber != 0) hash ^= RepoDesignDataNumber.GetHashCode();
          if (RepoDesignDataJSON.Length != 0) hash ^= RepoDesignDataJSON.GetHashCode();
          if (RepoDesignDataHash.Length != 0) hash ^= RepoDesignDataHash.GetHashCode();
          if (RepoDesignDataSilenceNumber != 0) hash ^= RepoDesignDataSilenceNumber.GetHashCode();
          if (RepoDesignDataSilenceJSON.Length != 0) hash ^= RepoDesignDataSilenceJSON.GetHashCode();
          if (RepoDesignDataSilenceHash.Length != 0) hash ^= RepoDesignDataSilenceHash.GetHashCode();
          if (EventVersionPreviewURL.Length != 0) hash ^= EventVersionPreviewURL.GetHashCode();
          if (EventFrontURL.Length != 0) hash ^= EventFrontURL.GetHashCode();
          if (GameCodename.Length != 0) hash ^= GameCodename.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ServerProtoIP.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ServerProtoIP);
          }
          if (ServerProtoPort != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ServerProtoPort);
          }
          if (ServerOAURL.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ServerOAURL);
          }
          if (ServerName.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(ServerName);
          }
          if (RepoResVersionURL.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(RepoResVersionURL);
          }
          if (RepoDesignDataURL.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(RepoDesignDataURL);
          }
          if (ServerServiceCenterURL.Length != 0) {
            output.WriteRawTag(82);
            output.WriteString(ServerServiceCenterURL);
          }
          if (ServerProtoVersion.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(ServerProtoVersion);
          }
          if (RepoDesignDataNumber != 0) {
            output.WriteRawTag(112);
            output.WriteUInt32(RepoDesignDataNumber);
          }
          if (EventVersionPreviewURL.Length != 0) {
            output.WriteRawTag(130, 1);
            output.WriteString(EventVersionPreviewURL);
          }
          if (RepoDesignDataSilenceNumber != 0) {
            output.WriteRawTag(144, 1);
            output.WriteUInt32(RepoDesignDataSilenceNumber);
          }
          if (RepoDesignDataJSON.Length != 0) {
            output.WriteRawTag(154, 1);
            output.WriteString(RepoDesignDataJSON);
          }
          if (RepoDesignDataSilenceJSON.Length != 0) {
            output.WriteRawTag(162, 1);
            output.WriteString(RepoDesignDataSilenceJSON);
          }
          if (repoResVersionProperties_ != null) {
            output.WriteRawTag(178, 1);
            output.WriteMessage(RepoResVersionProperties);
          }
          if (ServerProtoPubKey.Length != 0) {
            output.WriteRawTag(186, 1);
            output.WriteBytes(ServerProtoPubKey);
          }
          if (EventFrontURL.Length != 0) {
            output.WriteRawTag(194, 1);
            output.WriteString(EventFrontURL);
          }
          if (RepoDesignDataHash.Length != 0) {
            output.WriteRawTag(210, 1);
            output.WriteString(RepoDesignDataHash);
          }
          if (RepoDesignDataSilenceHash.Length != 0) {
            output.WriteRawTag(218, 1);
            output.WriteString(RepoDesignDataSilenceHash);
          }
          if (ServerLoginURL.Length != 0) {
            output.WriteRawTag(250, 1);
            output.WriteString(ServerLoginURL);
          }
          if (ServerCDKeyURL.Length != 0) {
            output.WriteRawTag(130, 2);
            output.WriteString(ServerCDKeyURL);
          }
          if (ServerAgreementURL.Length != 0) {
            output.WriteRawTag(138, 2);
            output.WriteString(ServerAgreementURL);
          }
          if (GameCodename.Length != 0) {
            output.WriteRawTag(162, 2);
            output.WriteString(GameCodename);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ServerProtoIP.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ServerProtoIP);
          }
          if (ServerProtoPort != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ServerProtoPort);
          }
          if (ServerOAURL.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ServerOAURL);
          }
          if (ServerName.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(ServerName);
          }
          if (RepoResVersionURL.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(RepoResVersionURL);
          }
          if (RepoDesignDataURL.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(RepoDesignDataURL);
          }
          if (ServerServiceCenterURL.Length != 0) {
            output.WriteRawTag(82);
            output.WriteString(ServerServiceCenterURL);
          }
          if (ServerProtoVersion.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(ServerProtoVersion);
          }
          if (RepoDesignDataNumber != 0) {
            output.WriteRawTag(112);
            output.WriteUInt32(RepoDesignDataNumber);
          }
          if (EventVersionPreviewURL.Length != 0) {
            output.WriteRawTag(130, 1);
            output.WriteString(EventVersionPreviewURL);
          }
          if (RepoDesignDataSilenceNumber != 0) {
            output.WriteRawTag(144, 1);
            output.WriteUInt32(RepoDesignDataSilenceNumber);
          }
          if (RepoDesignDataJSON.Length != 0) {
            output.WriteRawTag(154, 1);
            output.WriteString(RepoDesignDataJSON);
          }
          if (RepoDesignDataSilenceJSON.Length != 0) {
            output.WriteRawTag(162, 1);
            output.WriteString(RepoDesignDataSilenceJSON);
          }
          if (repoResVersionProperties_ != null) {
            output.WriteRawTag(178, 1);
            output.WriteMessage(RepoResVersionProperties);
          }
          if (ServerProtoPubKey.Length != 0) {
            output.WriteRawTag(186, 1);
            output.WriteBytes(ServerProtoPubKey);
          }
          if (EventFrontURL.Length != 0) {
            output.WriteRawTag(194, 1);
            output.WriteString(EventFrontURL);
          }
          if (RepoDesignDataHash.Length != 0) {
            output.WriteRawTag(210, 1);
            output.WriteString(RepoDesignDataHash);
          }
          if (RepoDesignDataSilenceHash.Length != 0) {
            output.WriteRawTag(218, 1);
            output.WriteString(RepoDesignDataSilenceHash);
          }
          if (ServerLoginURL.Length != 0) {
            output.WriteRawTag(250, 1);
            output.WriteString(ServerLoginURL);
          }
          if (ServerCDKeyURL.Length != 0) {
            output.WriteRawTag(130, 2);
            output.WriteString(ServerCDKeyURL);
          }
          if (ServerAgreementURL.Length != 0) {
            output.WriteRawTag(138, 2);
            output.WriteString(ServerAgreementURL);
          }
          if (GameCodename.Length != 0) {
            output.WriteRawTag(162, 2);
            output.WriteString(GameCodename);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ServerName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerName);
          }
          if (ServerOAURL.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerOAURL);
          }
          if (ServerServiceCenterURL.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerServiceCenterURL);
          }
          if (ServerLoginURL.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerLoginURL);
          }
          if (ServerCDKeyURL.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerCDKeyURL);
          }
          if (ServerAgreementURL.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerAgreementURL);
          }
          if (ServerProtoIP.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerProtoIP);
          }
          if (ServerProtoPort != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ServerProtoPort);
          }
          if (ServerProtoVersion.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerProtoVersion);
          }
          if (ServerProtoPubKey.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeBytesSize(ServerProtoPubKey);
          }
          if (RepoResVersionURL.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoResVersionURL);
          }
          if (repoResVersionProperties_ != null) {
            size += 2 + pb::CodedOutputStream.ComputeMessageSize(RepoResVersionProperties);
          }
          if (RepoDesignDataURL.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataURL);
          }
          if (RepoDesignDataNumber != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RepoDesignDataNumber);
          }
          if (RepoDesignDataJSON.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataJSON);
          }
          if (RepoDesignDataHash.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataHash);
          }
          if (RepoDesignDataSilenceNumber != 0) {
            size += 2 + pb::CodedOutputStream.ComputeUInt32Size(RepoDesignDataSilenceNumber);
          }
          if (RepoDesignDataSilenceJSON.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataSilenceJSON);
          }
          if (RepoDesignDataSilenceHash.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataSilenceHash);
          }
          if (EventVersionPreviewURL.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(EventVersionPreviewURL);
          }
          if (EventFrontURL.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(EventFrontURL);
          }
          if (GameCodename.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(GameCodename);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Properties other) {
          if (other == null) {
            return;
          }
          if (other.ServerName.Length != 0) {
            ServerName = other.ServerName;
          }
          if (other.ServerOAURL.Length != 0) {
            ServerOAURL = other.ServerOAURL;
          }
          if (other.ServerServiceCenterURL.Length != 0) {
            ServerServiceCenterURL = other.ServerServiceCenterURL;
          }
          if (other.ServerLoginURL.Length != 0) {
            ServerLoginURL = other.ServerLoginURL;
          }
          if (other.ServerCDKeyURL.Length != 0) {
            ServerCDKeyURL = other.ServerCDKeyURL;
          }
          if (other.ServerAgreementURL.Length != 0) {
            ServerAgreementURL = other.ServerAgreementURL;
          }
          if (other.ServerProtoIP.Length != 0) {
            ServerProtoIP = other.ServerProtoIP;
          }
          if (other.ServerProtoPort != 0) {
            ServerProtoPort = other.ServerProtoPort;
          }
          if (other.ServerProtoVersion.Length != 0) {
            ServerProtoVersion = other.ServerProtoVersion;
          }
          if (other.ServerProtoPubKey.Length != 0) {
            ServerProtoPubKey = other.ServerProtoPubKey;
          }
          if (other.RepoResVersionURL.Length != 0) {
            RepoResVersionURL = other.RepoResVersionURL;
          }
          if (other.repoResVersionProperties_ != null) {
            if (repoResVersionProperties_ == null) {
              RepoResVersionProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion();
            }
            RepoResVersionProperties.MergeFrom(other.RepoResVersionProperties);
          }
          if (other.RepoDesignDataURL.Length != 0) {
            RepoDesignDataURL = other.RepoDesignDataURL;
          }
          if (other.RepoDesignDataNumber != 0) {
            RepoDesignDataNumber = other.RepoDesignDataNumber;
          }
          if (other.RepoDesignDataJSON.Length != 0) {
            RepoDesignDataJSON = other.RepoDesignDataJSON;
          }
          if (other.RepoDesignDataHash.Length != 0) {
            RepoDesignDataHash = other.RepoDesignDataHash;
          }
          if (other.RepoDesignDataSilenceNumber != 0) {
            RepoDesignDataSilenceNumber = other.RepoDesignDataSilenceNumber;
          }
          if (other.RepoDesignDataSilenceJSON.Length != 0) {
            RepoDesignDataSilenceJSON = other.RepoDesignDataSilenceJSON;
          }
          if (other.RepoDesignDataSilenceHash.Length != 0) {
            RepoDesignDataSilenceHash = other.RepoDesignDataSilenceHash;
          }
          if (other.EventVersionPreviewURL.Length != 0) {
            EventVersionPreviewURL = other.EventVersionPreviewURL;
          }
          if (other.EventFrontURL.Length != 0) {
            EventFrontURL = other.EventFrontURL;
          }
          if (other.GameCodename.Length != 0) {
            GameCodename = other.GameCodename;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ServerProtoIP = input.ReadString();
                break;
              }
              case 16: {
                ServerProtoPort = input.ReadUInt32();
                break;
              }
              case 26: {
                ServerOAURL = input.ReadString();
                break;
              }
              case 58: {
                ServerName = input.ReadString();
                break;
              }
              case 66: {
                RepoResVersionURL = input.ReadString();
                break;
              }
              case 74: {
                RepoDesignDataURL = input.ReadString();
                break;
              }
              case 82: {
                ServerServiceCenterURL = input.ReadString();
                break;
              }
              case 98: {
                ServerProtoVersion = input.ReadString();
                break;
              }
              case 112: {
                RepoDesignDataNumber = input.ReadUInt32();
                break;
              }
              case 130: {
                EventVersionPreviewURL = input.ReadString();
                break;
              }
              case 144: {
                RepoDesignDataSilenceNumber = input.ReadUInt32();
                break;
              }
              case 154: {
                RepoDesignDataJSON = input.ReadString();
                break;
              }
              case 162: {
                RepoDesignDataSilenceJSON = input.ReadString();
                break;
              }
              case 178: {
                if (repoResVersionProperties_ == null) {
                  RepoResVersionProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion();
                }
                input.ReadMessage(RepoResVersionProperties);
                break;
              }
              case 186: {
                ServerProtoPubKey = input.ReadBytes();
                break;
              }
              case 194: {
                EventFrontURL = input.ReadString();
                break;
              }
              case 210: {
                RepoDesignDataHash = input.ReadString();
                break;
              }
              case 218: {
                RepoDesignDataSilenceHash = input.ReadString();
                break;
              }
              case 250: {
                ServerLoginURL = input.ReadString();
                break;
              }
              case 258: {
                ServerCDKeyURL = input.ReadString();
                break;
              }
              case 266: {
                ServerAgreementURL = input.ReadString();
                break;
              }
              case 290: {
                GameCodename = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                ServerProtoIP = input.ReadString();
                break;
              }
              case 16: {
                ServerProtoPort = input.ReadUInt32();
                break;
              }
              case 26: {
                ServerOAURL = input.ReadString();
                break;
              }
              case 58: {
                ServerName = input.ReadString();
                break;
              }
              case 66: {
                RepoResVersionURL = input.ReadString();
                break;
              }
              case 74: {
                RepoDesignDataURL = input.ReadString();
                break;
              }
              case 82: {
                ServerServiceCenterURL = input.ReadString();
                break;
              }
              case 98: {
                ServerProtoVersion = input.ReadString();
                break;
              }
              case 112: {
                RepoDesignDataNumber = input.ReadUInt32();
                break;
              }
              case 130: {
                EventVersionPreviewURL = input.ReadString();
                break;
              }
              case 144: {
                RepoDesignDataSilenceNumber = input.ReadUInt32();
                break;
              }
              case 154: {
                RepoDesignDataJSON = input.ReadString();
                break;
              }
              case 162: {
                RepoDesignDataSilenceJSON = input.ReadString();
                break;
              }
              case 178: {
                if (repoResVersionProperties_ == null) {
                  RepoResVersionProperties = new global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Types.ResVersion();
                }
                input.ReadMessage(RepoResVersionProperties);
                break;
              }
              case 186: {
                ServerProtoPubKey = input.ReadBytes();
                break;
              }
              case 194: {
                EventFrontURL = input.ReadString();
                break;
              }
              case 210: {
                RepoDesignDataHash = input.ReadString();
                break;
              }
              case 218: {
                RepoDesignDataSilenceHash = input.ReadString();
                break;
              }
              case 250: {
                ServerLoginURL = input.ReadString();
                break;
              }
              case 258: {
                ServerCDKeyURL = input.ReadString();
                break;
              }
              case 266: {
                ServerAgreementURL = input.ReadString();
                break;
              }
              case 290: {
                GameCodename = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Properties message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class ResVersion : pb::IMessage<ResVersion>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ResVersion> _parser = new pb::MessageParser<ResVersion>(() => new ResVersion());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ResVersion> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Hi3Helper.EncTool.Proto.Genshin.GenshinGateway.Types.Properties.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ResVersion() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ResVersion(ResVersion other) : this() {
              resVersionNumber_ = other.resVersionNumber_;
              resVersionMapJSON_ = other.resVersionMapJSON_;
              resVersionMinVersion_ = other.resVersionMinVersion_;
              resVersionHash_ = other.resVersionHash_;
              resVersion_ = other.resVersion_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ResVersion Clone() {
              return new ResVersion(this);
            }

            /// <summary>Field number for the "ResVersionNumber" field.</summary>
            public const int ResVersionNumberFieldNumber = 1;
            private uint resVersionNumber_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint ResVersionNumber {
              get { return resVersionNumber_; }
              set {
                resVersionNumber_ = value;
              }
            }

            /// <summary>Field number for the "ResVersionMapJSON" field.</summary>
            public const int ResVersionMapJSONFieldNumber = 3;
            private string resVersionMapJSON_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ResVersionMapJSON {
              get { return resVersionMapJSON_; }
              set {
                resVersionMapJSON_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "ResVersionMinVersion" field.</summary>
            public const int ResVersionMinVersionFieldNumber = 4;
            private string resVersionMinVersion_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ResVersionMinVersion {
              get { return resVersionMinVersion_; }
              set {
                resVersionMinVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "ResVersionHash" field.</summary>
            public const int ResVersionHashFieldNumber = 5;
            private string resVersionHash_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ResVersionHash {
              get { return resVersionHash_; }
              set {
                resVersionHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "ResVersion" field.</summary>
            public const int ResVersion_FieldNumber = 6;
            private string resVersion_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ResVersion_ {
              get { return resVersion_; }
              set {
                resVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ResVersion);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ResVersion other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (ResVersionNumber != other.ResVersionNumber) return false;
              if (ResVersionMapJSON != other.ResVersionMapJSON) return false;
              if (ResVersionMinVersion != other.ResVersionMinVersion) return false;
              if (ResVersionHash != other.ResVersionHash) return false;
              if (ResVersion_ != other.ResVersion_) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (ResVersionNumber != 0) hash ^= ResVersionNumber.GetHashCode();
              if (ResVersionMapJSON.Length != 0) hash ^= ResVersionMapJSON.GetHashCode();
              if (ResVersionMinVersion.Length != 0) hash ^= ResVersionMinVersion.GetHashCode();
              if (ResVersionHash.Length != 0) hash ^= ResVersionHash.GetHashCode();
              if (ResVersion_.Length != 0) hash ^= ResVersion_.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (ResVersionNumber != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(ResVersionNumber);
              }
              if (ResVersionMapJSON.Length != 0) {
                output.WriteRawTag(26);
                output.WriteString(ResVersionMapJSON);
              }
              if (ResVersionMinVersion.Length != 0) {
                output.WriteRawTag(34);
                output.WriteString(ResVersionMinVersion);
              }
              if (ResVersionHash.Length != 0) {
                output.WriteRawTag(42);
                output.WriteString(ResVersionHash);
              }
              if (ResVersion_.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(ResVersion_);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (ResVersionNumber != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(ResVersionNumber);
              }
              if (ResVersionMapJSON.Length != 0) {
                output.WriteRawTag(26);
                output.WriteString(ResVersionMapJSON);
              }
              if (ResVersionMinVersion.Length != 0) {
                output.WriteRawTag(34);
                output.WriteString(ResVersionMinVersion);
              }
              if (ResVersionHash.Length != 0) {
                output.WriteRawTag(42);
                output.WriteString(ResVersionHash);
              }
              if (ResVersion_.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(ResVersion_);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (ResVersionNumber != 0) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ResVersionNumber);
              }
              if (ResVersionMapJSON.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ResVersionMapJSON);
              }
              if (ResVersionMinVersion.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ResVersionMinVersion);
              }
              if (ResVersionHash.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ResVersionHash);
              }
              if (ResVersion_.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ResVersion_);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ResVersion other) {
              if (other == null) {
                return;
              }
              if (other.ResVersionNumber != 0) {
                ResVersionNumber = other.ResVersionNumber;
              }
              if (other.ResVersionMapJSON.Length != 0) {
                ResVersionMapJSON = other.ResVersionMapJSON;
              }
              if (other.ResVersionMinVersion.Length != 0) {
                ResVersionMinVersion = other.ResVersionMinVersion;
              }
              if (other.ResVersionHash.Length != 0) {
                ResVersionHash = other.ResVersionHash;
              }
              if (other.ResVersion_.Length != 0) {
                ResVersion_ = other.ResVersion_;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    ResVersionNumber = input.ReadUInt32();
                    break;
                  }
                  case 26: {
                    ResVersionMapJSON = input.ReadString();
                    break;
                  }
                  case 34: {
                    ResVersionMinVersion = input.ReadString();
                    break;
                  }
                  case 42: {
                    ResVersionHash = input.ReadString();
                    break;
                  }
                  case 50: {
                    ResVersion_ = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    ResVersionNumber = input.ReadUInt32();
                    break;
                  }
                  case 26: {
                    ResVersionMapJSON = input.ReadString();
                    break;
                  }
                  case 34: {
                    ResVersionMinVersion = input.ReadString();
                    break;
                  }
                  case 42: {
                    ResVersionHash = input.ReadString();
                    break;
                  }
                  case 50: {
                    ResVersion_ = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
