// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StarRailGateway.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hi3Helper.EncTool.Proto.StarRail {

  /// <summary>Holder for reflection information generated from StarRailGateway.proto</summary>
  public static partial class StarRailGatewayReflection {

    #region Descriptor
    /// <summary>File descriptor for StarRailGateway.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StarRailGatewayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTdGFyUmFpbEdhdGV3YXkucHJvdG8SIEhpM0hlbHBlci5FbmNUb29sLlBy",
            "b3RvLlN0YXJSYWlsIsEMCg9TdGFyUmFpbEdhdGV3YXkSIwobQXNzZXRCdW5k",
            "bGVWZXJzaW9uVXBkYXRlVXJsGAEgASgJEmAKFURlc2lnbkRhdGFSZWxvZ2lu",
            "VHlwZRgDIAEoDjJBLkhpM0hlbHBlci5FbmNUb29sLlByb3RvLlN0YXJSYWls",
            "LlN0YXJSYWlsR2F0ZXdheS5SZWxvZ2luVHlwZUNvZGUSIQoZTHVhQnVuZGxl",
            "VmVyc2lvblVwZGF0ZVVybBgEIAEoCRIrCiNFbmFibGVEZXNpZ25EYXRhQnVu",
            "ZGxlVmVyc2lvblVwZGF0ZRgFIAEoCBIoCiBEZXNpZ25EYXRhQnVuZGxlVmVy",
            "c2lvblVwZGF0ZVVybBgGIAEoCRIWCg5Bc2JSZWxvZ2luRGVzYxgHIAEoCRIM",
            "CgROYW1lGAkgASgJElkKDkFzYlJlbG9naW5UeXBlGAogASgOMkEuSGkzSGVs",
            "cGVyLkVuY1Rvb2wuUHJvdG8uU3RhclJhaWwuU3RhclJhaWxHYXRld2F5LlJl",
            "bG9naW5UeXBlQ29kZRIMCgRQb3J0GAsgASgNEiYKHkVuYWJsZUFzc2V0QnVu",
            "ZGxlVmVyc2lvblVwZGF0ZRgMIAEoCBIMCgRIb3N0GA0gASgJEhgKD0x1YVBh",
            "dGNoVmVyc2lvbhiOAiABKAkSFgoNbG9naW5XaGl0ZU1zZxjXAyABKAkSHgoV",
            "RGVzaWduRGF0YVJlbG9naW5EZXNjGJ4HIAEoCRIdChRwcmVkb3dubG9hZFVw",
            "ZGF0ZVVybBj8CSABKAkSGgoRSUZpeFBhdGNoUmV2aXNpb24YjwsgASgJEiIK",
            "GUlGaXhQYXRjaFZlcnNpb25VcGRhdGVVcmwYvwsgASgJEhUKDVN0b3BCZWdp",
            "blRpbWUYAiABKAMSEwoLU3RvcEVuZFRpbWUYCCABKAMSEAoIU3RvcERlc2MY",
            "DiABKAkSFwoOU2VydmVyVXJsRGljdDEYlQYgASgJEhYKDlNlcnZlclVybERp",
            "Y3QyGFcgASgJEhcKDlNlcnZlclVybERpY3QzGMsHIAEoCRIXCg5TZXJ2ZXJV",
            "cmxEaWN0NBiTBSABKAkSFwoOU2VydmVyVXJsRGljdDUYwAUgASgJEhcKDlNl",
            "cnZlclVybERpY3Q2GPELIAEoCRIXCg5TZXJ2ZXJVcmxEaWN0NxiBAyABKAkS",
            "FwoOU2VydmVyVXJsRGljdDgY1w0gASgJEhcKDlNlcnZlclVybERpY3Q5GLwI",
            "IAEoCRIYCg9TZXJ2ZXJVcmxEaWN0MTAY8QEgASgJEg8KBlVzZVRjcBj8DyAB",
            "KAgSHQoURW5hYmxlU2F2ZVJlcGxheUZpbGUYsgIgASgIEh4KFUVuYWJsZVVw",
            "bG9hZEJhdHRsZUxvZxi8CiABKAgSGgoRU2VydmVyRGVzY3JpcHRpb24Y8gEg",
            "ASgJEh4KFU9ubGluZVJlcGxheVVwbG9hZFVybBi8ASABKAkSIAoXT25saW5l",
            "UmVwbGF5RG93bmxvYWRVcmwY6w0gASgJEhkKEEVuYWJsZVJlZGVlbUNvZGUY",
            "nwMgASgIEhcKDkZvcmJpZFJlY2hhcmdlGPsMIAEoCBISCglNVFBTd2l0Y2gY",
            "rAUgASgIEhoKEUV2ZW50VHJhY2tpbmdPcGVuGKUEIAEoCBIQCgdJT1NFeGFt",
            "GNsIIAEoCBJgCgxEaXNwYXRjaEluZm8YDyABKA4ySi5IaTNIZWxwZXIuRW5j",
            "VG9vbC5Qcm90by5TdGFyUmFpbC5TdGFyUmFpbEdhdGV3YXkuU2VydmVyRGlz",
            "cGF0Y2hSZXR1cm5Db2RlIq8BChhTZXJ2ZXJEaXNwYXRjaFJldHVybkNvZGUS",
            "CwoHU3VjY2VzcxAAEgsKB0ZhaWx1cmUQARIOCgpTZXJ2ZXJTdG9wEAISEAoM",
            "VmVyc2lvbkVycm9yEAMSFAoQUkVUX0ZPUkNFX1VQREFURRAEEhYKElJFVF9M",
            "QU5HVUFHRV9FUlJPUhAFEhYKElJFVF9QTEFURk9STV9FUlJPUhAGEhEKDVJF",
            "VF9DRE5fRVJST1IQByJHCg9SZWxvZ2luVHlwZUNvZGUSCgoGTm9LaWNrEAAS",
            "DQoJRm9yY2VLaWNrEAESDAoISWRsZUtpY2sQAhILCgdTaWxlbmNlEANiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway), global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Parser, new[]{ "AssetBundleVersionUpdateUrl", "DesignDataReloginType", "LuaBundleVersionUpdateUrl", "EnableDesignDataBundleVersionUpdate", "DesignDataBundleVersionUpdateUrl", "AsbReloginDesc", "Name", "AsbReloginType", "Port", "EnableAssetBundleVersionUpdate", "Host", "LuaPatchVersion", "LoginWhiteMsg", "DesignDataReloginDesc", "PredownloadUpdateUrl", "IFixPatchRevision", "IFixPatchVersionUpdateUrl", "StopBeginTime", "StopEndTime", "StopDesc", "ServerUrlDict1", "ServerUrlDict2", "ServerUrlDict3", "ServerUrlDict4", "ServerUrlDict5", "ServerUrlDict6", "ServerUrlDict7", "ServerUrlDict8", "ServerUrlDict9", "ServerUrlDict10", "UseTcp", "EnableSaveReplayFile", "EnableUploadBattleLog", "ServerDescription", "OnlineReplayUploadUrl", "OnlineReplayDownloadUrl", "EnableRedeemCode", "ForbidRecharge", "MTPSwitch", "EventTrackingOpen", "IOSExam", "DispatchInfo" }, null, new[]{ typeof(global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode), typeof(global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StarRailGateway : pb::IMessage<StarRailGateway>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StarRailGateway> _parser = new pb::MessageParser<StarRailGateway>(() => new StarRailGateway());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StarRailGateway> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.EncTool.Proto.StarRail.StarRailGatewayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway(StarRailGateway other) : this() {
      assetBundleVersionUpdateUrl_ = other.assetBundleVersionUpdateUrl_;
      designDataReloginType_ = other.designDataReloginType_;
      luaBundleVersionUpdateUrl_ = other.luaBundleVersionUpdateUrl_;
      enableDesignDataBundleVersionUpdate_ = other.enableDesignDataBundleVersionUpdate_;
      designDataBundleVersionUpdateUrl_ = other.designDataBundleVersionUpdateUrl_;
      asbReloginDesc_ = other.asbReloginDesc_;
      name_ = other.name_;
      asbReloginType_ = other.asbReloginType_;
      port_ = other.port_;
      enableAssetBundleVersionUpdate_ = other.enableAssetBundleVersionUpdate_;
      host_ = other.host_;
      luaPatchVersion_ = other.luaPatchVersion_;
      loginWhiteMsg_ = other.loginWhiteMsg_;
      designDataReloginDesc_ = other.designDataReloginDesc_;
      predownloadUpdateUrl_ = other.predownloadUpdateUrl_;
      iFixPatchRevision_ = other.iFixPatchRevision_;
      iFixPatchVersionUpdateUrl_ = other.iFixPatchVersionUpdateUrl_;
      stopBeginTime_ = other.stopBeginTime_;
      stopEndTime_ = other.stopEndTime_;
      stopDesc_ = other.stopDesc_;
      serverUrlDict1_ = other.serverUrlDict1_;
      serverUrlDict2_ = other.serverUrlDict2_;
      serverUrlDict3_ = other.serverUrlDict3_;
      serverUrlDict4_ = other.serverUrlDict4_;
      serverUrlDict5_ = other.serverUrlDict5_;
      serverUrlDict6_ = other.serverUrlDict6_;
      serverUrlDict7_ = other.serverUrlDict7_;
      serverUrlDict8_ = other.serverUrlDict8_;
      serverUrlDict9_ = other.serverUrlDict9_;
      serverUrlDict10_ = other.serverUrlDict10_;
      useTcp_ = other.useTcp_;
      enableSaveReplayFile_ = other.enableSaveReplayFile_;
      enableUploadBattleLog_ = other.enableUploadBattleLog_;
      serverDescription_ = other.serverDescription_;
      onlineReplayUploadUrl_ = other.onlineReplayUploadUrl_;
      onlineReplayDownloadUrl_ = other.onlineReplayDownloadUrl_;
      enableRedeemCode_ = other.enableRedeemCode_;
      forbidRecharge_ = other.forbidRecharge_;
      mTPSwitch_ = other.mTPSwitch_;
      eventTrackingOpen_ = other.eventTrackingOpen_;
      iOSExam_ = other.iOSExam_;
      dispatchInfo_ = other.dispatchInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway Clone() {
      return new StarRailGateway(this);
    }

    /// <summary>Field number for the "AssetBundleVersionUpdateUrl" field.</summary>
    public const int AssetBundleVersionUpdateUrlFieldNumber = 1;
    private string assetBundleVersionUpdateUrl_ = "";
    /// <summary>
    /// AIKOOECPBDD (ID: CGJMIEFOCCO)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AssetBundleVersionUpdateUrl {
      get { return assetBundleVersionUpdateUrl_; }
      set {
        assetBundleVersionUpdateUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DesignDataReloginType" field.</summary>
    public const int DesignDataReloginTypeFieldNumber = 3;
    private global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode designDataReloginType_ = global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick;
    /// <summary>
    /// BJCFOMFMCFK (ID: OGGPLLHBIDA)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode DesignDataReloginType {
      get { return designDataReloginType_; }
      set {
        designDataReloginType_ = value;
      }
    }

    /// <summary>Field number for the "LuaBundleVersionUpdateUrl" field.</summary>
    public const int LuaBundleVersionUpdateUrlFieldNumber = 4;
    private string luaBundleVersionUpdateUrl_ = "";
    /// <summary>
    /// IBEIMOGAMGA (ID: GCFGGHNFNPA)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LuaBundleVersionUpdateUrl {
      get { return luaBundleVersionUpdateUrl_; }
      set {
        luaBundleVersionUpdateUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EnableDesignDataBundleVersionUpdate" field.</summary>
    public const int EnableDesignDataBundleVersionUpdateFieldNumber = 5;
    private bool enableDesignDataBundleVersionUpdate_;
    /// <summary>
    /// BMKALDCKHAJ (ID: CBKGDJPINIJ)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableDesignDataBundleVersionUpdate {
      get { return enableDesignDataBundleVersionUpdate_; }
      set {
        enableDesignDataBundleVersionUpdate_ = value;
      }
    }

    /// <summary>Field number for the "DesignDataBundleVersionUpdateUrl" field.</summary>
    public const int DesignDataBundleVersionUpdateUrlFieldNumber = 6;
    private string designDataBundleVersionUpdateUrl_ = "";
    /// <summary>
    /// IDNKMBGNKIL (ID: BIBHFBLBPJJ)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DesignDataBundleVersionUpdateUrl {
      get { return designDataBundleVersionUpdateUrl_; }
      set {
        designDataBundleVersionUpdateUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AsbReloginDesc" field.</summary>
    public const int AsbReloginDescFieldNumber = 7;
    private string asbReloginDesc_ = "";
    /// <summary>
    /// HOIPFMFLHHK (ID: OFBGHLGCDJH)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AsbReloginDesc {
      get { return asbReloginDesc_; }
      set {
        asbReloginDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 9;
    private string name_ = "";
    /// <summary>
    /// IKCHCOJCMPD (ID: DCCGHHKGFHD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AsbReloginType" field.</summary>
    public const int AsbReloginTypeFieldNumber = 10;
    private global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode asbReloginType_ = global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick;
    /// <summary>
    /// PGOMDHLJOPH (ID: GGIBIHBADDG)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode AsbReloginType {
      get { return asbReloginType_; }
      set {
        asbReloginType_ = value;
      }
    }

    /// <summary>Field number for the "Port" field.</summary>
    public const int PortFieldNumber = 11;
    private uint port_;
    /// <summary>
    /// JEFMFJPJGNP (ID: LMJLNMBDGJF)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "EnableAssetBundleVersionUpdate" field.</summary>
    public const int EnableAssetBundleVersionUpdateFieldNumber = 12;
    private bool enableAssetBundleVersionUpdate_;
    /// <summary>
    /// OBOMKLDGJEE (ID: LOOAFGDHODB)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableAssetBundleVersionUpdate {
      get { return enableAssetBundleVersionUpdate_; }
      set {
        enableAssetBundleVersionUpdate_ = value;
      }
    }

    /// <summary>Field number for the "Host" field.</summary>
    public const int HostFieldNumber = 13;
    private string host_ = "";
    /// <summary>
    /// FLAEJCLONHP (ID: JMDDFENIPBD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Host {
      get { return host_; }
      set {
        host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaPatchVersion" field.</summary>
    public const int LuaPatchVersionFieldNumber = 270;
    private string luaPatchVersion_ = "";
    /// <summary>
    /// MKHJMFGMBEP (ID: NFLMHAFPLIB)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LuaPatchVersion {
      get { return luaPatchVersion_; }
      set {
        luaPatchVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "loginWhiteMsg" field.</summary>
    public const int LoginWhiteMsgFieldNumber = 471;
    private string loginWhiteMsg_ = "";
    /// <summary>
    /// FBFCOIJPBGO (ID: NOIJIDEGNNO)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginWhiteMsg {
      get { return loginWhiteMsg_; }
      set {
        loginWhiteMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DesignDataReloginDesc" field.</summary>
    public const int DesignDataReloginDescFieldNumber = 926;
    private string designDataReloginDesc_ = "";
    /// <summary>
    /// BENMINCEINB (ID: IODJOCFACMI)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DesignDataReloginDesc {
      get { return designDataReloginDesc_; }
      set {
        designDataReloginDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "predownloadUpdateUrl" field.</summary>
    public const int PredownloadUpdateUrlFieldNumber = 1276;
    private string predownloadUpdateUrl_ = "";
    /// <summary>
    /// IKFBKCBANEP (ID: NDKLIDBFNPD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PredownloadUpdateUrl {
      get { return predownloadUpdateUrl_; }
      set {
        predownloadUpdateUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IFixPatchRevision" field.</summary>
    public const int IFixPatchRevisionFieldNumber = 1423;
    private string iFixPatchRevision_ = "";
    /// <summary>
    /// EMDBODLHPLO (ID: PGIJCGEANLB)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IFixPatchRevision {
      get { return iFixPatchRevision_; }
      set {
        iFixPatchRevision_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IFixPatchVersionUpdateUrl" field.</summary>
    public const int IFixPatchVersionUpdateUrlFieldNumber = 1471;
    private string iFixPatchVersionUpdateUrl_ = "";
    /// <summary>
    /// CALDCNKAOOC (ID: DNJOPGPODAF)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IFixPatchVersionUpdateUrl {
      get { return iFixPatchVersionUpdateUrl_; }
      set {
        iFixPatchVersionUpdateUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "StopBeginTime" field.</summary>
    public const int StopBeginTimeFieldNumber = 2;
    private long stopBeginTime_;
    /// <summary>
    /// NNKEGHJFMNI (ID: NHIOLGGDGJI)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StopBeginTime {
      get { return stopBeginTime_; }
      set {
        stopBeginTime_ = value;
      }
    }

    /// <summary>Field number for the "StopEndTime" field.</summary>
    public const int StopEndTimeFieldNumber = 8;
    private long stopEndTime_;
    /// <summary>
    /// EIPHLGAIMNC (ID: FCBHJIKANFA)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StopEndTime {
      get { return stopEndTime_; }
      set {
        stopEndTime_ = value;
      }
    }

    /// <summary>Field number for the "StopDesc" field.</summary>
    public const int StopDescFieldNumber = 14;
    private string stopDesc_ = "";
    /// <summary>
    /// GJLKPCECODB (ID: GDHDLOHEGMJ)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StopDesc {
      get { return stopDesc_; }
      set {
        stopDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict1" field.</summary>
    public const int ServerUrlDict1FieldNumber = 789;
    private string serverUrlDict1_ = "";
    /// <summary>
    /// FEGCFGOCLBC (ID: IGNKGIMGNHK)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict1 {
      get { return serverUrlDict1_; }
      set {
        serverUrlDict1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict2" field.</summary>
    public const int ServerUrlDict2FieldNumber = 87;
    private string serverUrlDict2_ = "";
    /// <summary>
    /// GCABNHLBOIM (ID: AOHDOKCDECN)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict2 {
      get { return serverUrlDict2_; }
      set {
        serverUrlDict2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict3" field.</summary>
    public const int ServerUrlDict3FieldNumber = 971;
    private string serverUrlDict3_ = "";
    /// <summary>
    /// DINFFHGNGJM (ID: FAGJGKGDGNH)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict3 {
      get { return serverUrlDict3_; }
      set {
        serverUrlDict3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict4" field.</summary>
    public const int ServerUrlDict4FieldNumber = 659;
    private string serverUrlDict4_ = "";
    /// <summary>
    /// BCOMKKNJABD (ID: GJMLCLJLBOA)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict4 {
      get { return serverUrlDict4_; }
      set {
        serverUrlDict4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict5" field.</summary>
    public const int ServerUrlDict5FieldNumber = 704;
    private string serverUrlDict5_ = "";
    /// <summary>
    /// JPHBIKEGMHK (ID: EIDBKLDJGEB)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict5 {
      get { return serverUrlDict5_; }
      set {
        serverUrlDict5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict6" field.</summary>
    public const int ServerUrlDict6FieldNumber = 1521;
    private string serverUrlDict6_ = "";
    /// <summary>
    /// JEJFEKODNJI (ID: NGPOIJCAFBJ)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict6 {
      get { return serverUrlDict6_; }
      set {
        serverUrlDict6_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict7" field.</summary>
    public const int ServerUrlDict7FieldNumber = 385;
    private string serverUrlDict7_ = "";
    /// <summary>
    /// EDJCFNAJIHE (ID: CEIJLIIJKLD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict7 {
      get { return serverUrlDict7_; }
      set {
        serverUrlDict7_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict8" field.</summary>
    public const int ServerUrlDict8FieldNumber = 1751;
    private string serverUrlDict8_ = "";
    /// <summary>
    /// KDPOOELNBPP (ID: JJDLBDJOHPE)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict8 {
      get { return serverUrlDict8_; }
      set {
        serverUrlDict8_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict9" field.</summary>
    public const int ServerUrlDict9FieldNumber = 1084;
    private string serverUrlDict9_ = "";
    /// <summary>
    /// KDGMBDCEONC (ID: NFCPHIODPLI)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict9 {
      get { return serverUrlDict9_; }
      set {
        serverUrlDict9_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerUrlDict10" field.</summary>
    public const int ServerUrlDict10FieldNumber = 241;
    private string serverUrlDict10_ = "";
    /// <summary>
    /// DHOKJOICDGD (ID: JHLJJBAKFOC)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrlDict10 {
      get { return serverUrlDict10_; }
      set {
        serverUrlDict10_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UseTcp" field.</summary>
    public const int UseTcpFieldNumber = 2044;
    private bool useTcp_;
    /// <summary>
    /// FNHPEALEAHC (ID: GGOLCPDLLGA)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UseTcp {
      get { return useTcp_; }
      set {
        useTcp_ = value;
      }
    }

    /// <summary>Field number for the "EnableSaveReplayFile" field.</summary>
    public const int EnableSaveReplayFileFieldNumber = 306;
    private bool enableSaveReplayFile_;
    /// <summary>
    /// GMKEGAOOBPI (ID: APMLEGLHFHD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableSaveReplayFile {
      get { return enableSaveReplayFile_; }
      set {
        enableSaveReplayFile_ = value;
      }
    }

    /// <summary>Field number for the "EnableUploadBattleLog" field.</summary>
    public const int EnableUploadBattleLogFieldNumber = 1340;
    private bool enableUploadBattleLog_;
    /// <summary>
    /// JFLAHKKOJBP (ID: OAOFAAEPGOD)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableUploadBattleLog {
      get { return enableUploadBattleLog_; }
      set {
        enableUploadBattleLog_ = value;
      }
    }

    /// <summary>Field number for the "ServerDescription" field.</summary>
    public const int ServerDescriptionFieldNumber = 242;
    private string serverDescription_ = "";
    /// <summary>
    /// HKNFIHHKHGF (ID: MCPODGKNNKJ)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerDescription {
      get { return serverDescription_; }
      set {
        serverDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OnlineReplayUploadUrl" field.</summary>
    public const int OnlineReplayUploadUrlFieldNumber = 188;
    private string onlineReplayUploadUrl_ = "";
    /// <summary>
    /// DINPGLAFGNL (ID: AEPNLIPJALP)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OnlineReplayUploadUrl {
      get { return onlineReplayUploadUrl_; }
      set {
        onlineReplayUploadUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OnlineReplayDownloadUrl" field.</summary>
    public const int OnlineReplayDownloadUrlFieldNumber = 1771;
    private string onlineReplayDownloadUrl_ = "";
    /// <summary>
    /// GIGMBOMLCOL (ID: PLAAFMIMEAF)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OnlineReplayDownloadUrl {
      get { return onlineReplayDownloadUrl_; }
      set {
        onlineReplayDownloadUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EnableRedeemCode" field.</summary>
    public const int EnableRedeemCodeFieldNumber = 415;
    private bool enableRedeemCode_;
    /// <summary>
    /// FOIJNCKDHNK (ID: CDNACJDFOBI)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableRedeemCode {
      get { return enableRedeemCode_; }
      set {
        enableRedeemCode_ = value;
      }
    }

    /// <summary>Field number for the "ForbidRecharge" field.</summary>
    public const int ForbidRechargeFieldNumber = 1659;
    private bool forbidRecharge_;
    /// <summary>
    /// DBOACCLGMEC (ID: BAAMPBFABKO)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ForbidRecharge {
      get { return forbidRecharge_; }
      set {
        forbidRecharge_ = value;
      }
    }

    /// <summary>Field number for the "MTPSwitch" field.</summary>
    public const int MTPSwitchFieldNumber = 684;
    private bool mTPSwitch_;
    /// <summary>
    /// JOOBMKHDODK (ID: GMPLEKIEHHE)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MTPSwitch {
      get { return mTPSwitch_; }
      set {
        mTPSwitch_ = value;
      }
    }

    /// <summary>Field number for the "EventTrackingOpen" field.</summary>
    public const int EventTrackingOpenFieldNumber = 549;
    private bool eventTrackingOpen_;
    /// <summary>
    /// EHPIEINBAAK (ID: NALOBJGAOCN)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EventTrackingOpen {
      get { return eventTrackingOpen_; }
      set {
        eventTrackingOpen_ = value;
      }
    }

    /// <summary>Field number for the "IOSExam" field.</summary>
    public const int IOSExamFieldNumber = 1115;
    private bool iOSExam_;
    /// <summary>
    /// BPFFNLHNCLI (ID: APOMFMHPLNL)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IOSExam {
      get { return iOSExam_; }
      set {
        iOSExam_ = value;
      }
    }

    /// <summary>Field number for the "DispatchInfo" field.</summary>
    public const int DispatchInfoFieldNumber = 15;
    private global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode dispatchInfo_ = global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success;
    /// <summary>
    /// IBIOCHNGJKO (ID: HFCDDOBFELF)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode DispatchInfo {
      get { return dispatchInfo_; }
      set {
        dispatchInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StarRailGateway);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StarRailGateway other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AssetBundleVersionUpdateUrl != other.AssetBundleVersionUpdateUrl) return false;
      if (DesignDataReloginType != other.DesignDataReloginType) return false;
      if (LuaBundleVersionUpdateUrl != other.LuaBundleVersionUpdateUrl) return false;
      if (EnableDesignDataBundleVersionUpdate != other.EnableDesignDataBundleVersionUpdate) return false;
      if (DesignDataBundleVersionUpdateUrl != other.DesignDataBundleVersionUpdateUrl) return false;
      if (AsbReloginDesc != other.AsbReloginDesc) return false;
      if (Name != other.Name) return false;
      if (AsbReloginType != other.AsbReloginType) return false;
      if (Port != other.Port) return false;
      if (EnableAssetBundleVersionUpdate != other.EnableAssetBundleVersionUpdate) return false;
      if (Host != other.Host) return false;
      if (LuaPatchVersion != other.LuaPatchVersion) return false;
      if (LoginWhiteMsg != other.LoginWhiteMsg) return false;
      if (DesignDataReloginDesc != other.DesignDataReloginDesc) return false;
      if (PredownloadUpdateUrl != other.PredownloadUpdateUrl) return false;
      if (IFixPatchRevision != other.IFixPatchRevision) return false;
      if (IFixPatchVersionUpdateUrl != other.IFixPatchVersionUpdateUrl) return false;
      if (StopBeginTime != other.StopBeginTime) return false;
      if (StopEndTime != other.StopEndTime) return false;
      if (StopDesc != other.StopDesc) return false;
      if (ServerUrlDict1 != other.ServerUrlDict1) return false;
      if (ServerUrlDict2 != other.ServerUrlDict2) return false;
      if (ServerUrlDict3 != other.ServerUrlDict3) return false;
      if (ServerUrlDict4 != other.ServerUrlDict4) return false;
      if (ServerUrlDict5 != other.ServerUrlDict5) return false;
      if (ServerUrlDict6 != other.ServerUrlDict6) return false;
      if (ServerUrlDict7 != other.ServerUrlDict7) return false;
      if (ServerUrlDict8 != other.ServerUrlDict8) return false;
      if (ServerUrlDict9 != other.ServerUrlDict9) return false;
      if (ServerUrlDict10 != other.ServerUrlDict10) return false;
      if (UseTcp != other.UseTcp) return false;
      if (EnableSaveReplayFile != other.EnableSaveReplayFile) return false;
      if (EnableUploadBattleLog != other.EnableUploadBattleLog) return false;
      if (ServerDescription != other.ServerDescription) return false;
      if (OnlineReplayUploadUrl != other.OnlineReplayUploadUrl) return false;
      if (OnlineReplayDownloadUrl != other.OnlineReplayDownloadUrl) return false;
      if (EnableRedeemCode != other.EnableRedeemCode) return false;
      if (ForbidRecharge != other.ForbidRecharge) return false;
      if (MTPSwitch != other.MTPSwitch) return false;
      if (EventTrackingOpen != other.EventTrackingOpen) return false;
      if (IOSExam != other.IOSExam) return false;
      if (DispatchInfo != other.DispatchInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AssetBundleVersionUpdateUrl.Length != 0) hash ^= AssetBundleVersionUpdateUrl.GetHashCode();
      if (DesignDataReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) hash ^= DesignDataReloginType.GetHashCode();
      if (LuaBundleVersionUpdateUrl.Length != 0) hash ^= LuaBundleVersionUpdateUrl.GetHashCode();
      if (EnableDesignDataBundleVersionUpdate != false) hash ^= EnableDesignDataBundleVersionUpdate.GetHashCode();
      if (DesignDataBundleVersionUpdateUrl.Length != 0) hash ^= DesignDataBundleVersionUpdateUrl.GetHashCode();
      if (AsbReloginDesc.Length != 0) hash ^= AsbReloginDesc.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (AsbReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) hash ^= AsbReloginType.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (EnableAssetBundleVersionUpdate != false) hash ^= EnableAssetBundleVersionUpdate.GetHashCode();
      if (Host.Length != 0) hash ^= Host.GetHashCode();
      if (LuaPatchVersion.Length != 0) hash ^= LuaPatchVersion.GetHashCode();
      if (LoginWhiteMsg.Length != 0) hash ^= LoginWhiteMsg.GetHashCode();
      if (DesignDataReloginDesc.Length != 0) hash ^= DesignDataReloginDesc.GetHashCode();
      if (PredownloadUpdateUrl.Length != 0) hash ^= PredownloadUpdateUrl.GetHashCode();
      if (IFixPatchRevision.Length != 0) hash ^= IFixPatchRevision.GetHashCode();
      if (IFixPatchVersionUpdateUrl.Length != 0) hash ^= IFixPatchVersionUpdateUrl.GetHashCode();
      if (StopBeginTime != 0L) hash ^= StopBeginTime.GetHashCode();
      if (StopEndTime != 0L) hash ^= StopEndTime.GetHashCode();
      if (StopDesc.Length != 0) hash ^= StopDesc.GetHashCode();
      if (ServerUrlDict1.Length != 0) hash ^= ServerUrlDict1.GetHashCode();
      if (ServerUrlDict2.Length != 0) hash ^= ServerUrlDict2.GetHashCode();
      if (ServerUrlDict3.Length != 0) hash ^= ServerUrlDict3.GetHashCode();
      if (ServerUrlDict4.Length != 0) hash ^= ServerUrlDict4.GetHashCode();
      if (ServerUrlDict5.Length != 0) hash ^= ServerUrlDict5.GetHashCode();
      if (ServerUrlDict6.Length != 0) hash ^= ServerUrlDict6.GetHashCode();
      if (ServerUrlDict7.Length != 0) hash ^= ServerUrlDict7.GetHashCode();
      if (ServerUrlDict8.Length != 0) hash ^= ServerUrlDict8.GetHashCode();
      if (ServerUrlDict9.Length != 0) hash ^= ServerUrlDict9.GetHashCode();
      if (ServerUrlDict10.Length != 0) hash ^= ServerUrlDict10.GetHashCode();
      if (UseTcp != false) hash ^= UseTcp.GetHashCode();
      if (EnableSaveReplayFile != false) hash ^= EnableSaveReplayFile.GetHashCode();
      if (EnableUploadBattleLog != false) hash ^= EnableUploadBattleLog.GetHashCode();
      if (ServerDescription.Length != 0) hash ^= ServerDescription.GetHashCode();
      if (OnlineReplayUploadUrl.Length != 0) hash ^= OnlineReplayUploadUrl.GetHashCode();
      if (OnlineReplayDownloadUrl.Length != 0) hash ^= OnlineReplayDownloadUrl.GetHashCode();
      if (EnableRedeemCode != false) hash ^= EnableRedeemCode.GetHashCode();
      if (ForbidRecharge != false) hash ^= ForbidRecharge.GetHashCode();
      if (MTPSwitch != false) hash ^= MTPSwitch.GetHashCode();
      if (EventTrackingOpen != false) hash ^= EventTrackingOpen.GetHashCode();
      if (IOSExam != false) hash ^= IOSExam.GetHashCode();
      if (DispatchInfo != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success) hash ^= DispatchInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AssetBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetBundleVersionUpdateUrl);
      }
      if (StopBeginTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StopBeginTime);
      }
      if (DesignDataReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DesignDataReloginType);
      }
      if (LuaBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LuaBundleVersionUpdateUrl);
      }
      if (EnableDesignDataBundleVersionUpdate != false) {
        output.WriteRawTag(40);
        output.WriteBool(EnableDesignDataBundleVersionUpdate);
      }
      if (DesignDataBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DesignDataBundleVersionUpdateUrl);
      }
      if (AsbReloginDesc.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AsbReloginDesc);
      }
      if (StopEndTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(StopEndTime);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (AsbReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        output.WriteRawTag(80);
        output.WriteEnum((int) AsbReloginType);
      }
      if (Port != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Port);
      }
      if (EnableAssetBundleVersionUpdate != false) {
        output.WriteRawTag(96);
        output.WriteBool(EnableAssetBundleVersionUpdate);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Host);
      }
      if (StopDesc.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StopDesc);
      }
      if (DispatchInfo != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success) {
        output.WriteRawTag(120);
        output.WriteEnum((int) DispatchInfo);
      }
      if (ServerUrlDict2.Length != 0) {
        output.WriteRawTag(186, 5);
        output.WriteString(ServerUrlDict2);
      }
      if (OnlineReplayUploadUrl.Length != 0) {
        output.WriteRawTag(226, 11);
        output.WriteString(OnlineReplayUploadUrl);
      }
      if (ServerUrlDict10.Length != 0) {
        output.WriteRawTag(138, 15);
        output.WriteString(ServerUrlDict10);
      }
      if (ServerDescription.Length != 0) {
        output.WriteRawTag(146, 15);
        output.WriteString(ServerDescription);
      }
      if (LuaPatchVersion.Length != 0) {
        output.WriteRawTag(242, 16);
        output.WriteString(LuaPatchVersion);
      }
      if (EnableSaveReplayFile != false) {
        output.WriteRawTag(144, 19);
        output.WriteBool(EnableSaveReplayFile);
      }
      if (ServerUrlDict7.Length != 0) {
        output.WriteRawTag(138, 24);
        output.WriteString(ServerUrlDict7);
      }
      if (EnableRedeemCode != false) {
        output.WriteRawTag(248, 25);
        output.WriteBool(EnableRedeemCode);
      }
      if (LoginWhiteMsg.Length != 0) {
        output.WriteRawTag(186, 29);
        output.WriteString(LoginWhiteMsg);
      }
      if (EventTrackingOpen != false) {
        output.WriteRawTag(168, 34);
        output.WriteBool(EventTrackingOpen);
      }
      if (ServerUrlDict4.Length != 0) {
        output.WriteRawTag(154, 41);
        output.WriteString(ServerUrlDict4);
      }
      if (MTPSwitch != false) {
        output.WriteRawTag(224, 42);
        output.WriteBool(MTPSwitch);
      }
      if (ServerUrlDict5.Length != 0) {
        output.WriteRawTag(130, 44);
        output.WriteString(ServerUrlDict5);
      }
      if (ServerUrlDict1.Length != 0) {
        output.WriteRawTag(170, 49);
        output.WriteString(ServerUrlDict1);
      }
      if (DesignDataReloginDesc.Length != 0) {
        output.WriteRawTag(242, 57);
        output.WriteString(DesignDataReloginDesc);
      }
      if (ServerUrlDict3.Length != 0) {
        output.WriteRawTag(218, 60);
        output.WriteString(ServerUrlDict3);
      }
      if (ServerUrlDict9.Length != 0) {
        output.WriteRawTag(226, 67);
        output.WriteString(ServerUrlDict9);
      }
      if (IOSExam != false) {
        output.WriteRawTag(216, 69);
        output.WriteBool(IOSExam);
      }
      if (PredownloadUpdateUrl.Length != 0) {
        output.WriteRawTag(226, 79);
        output.WriteString(PredownloadUpdateUrl);
      }
      if (EnableUploadBattleLog != false) {
        output.WriteRawTag(224, 83);
        output.WriteBool(EnableUploadBattleLog);
      }
      if (IFixPatchRevision.Length != 0) {
        output.WriteRawTag(250, 88);
        output.WriteString(IFixPatchRevision);
      }
      if (IFixPatchVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(250, 91);
        output.WriteString(IFixPatchVersionUpdateUrl);
      }
      if (ServerUrlDict6.Length != 0) {
        output.WriteRawTag(138, 95);
        output.WriteString(ServerUrlDict6);
      }
      if (ForbidRecharge != false) {
        output.WriteRawTag(216, 103);
        output.WriteBool(ForbidRecharge);
      }
      if (ServerUrlDict8.Length != 0) {
        output.WriteRawTag(186, 109);
        output.WriteString(ServerUrlDict8);
      }
      if (OnlineReplayDownloadUrl.Length != 0) {
        output.WriteRawTag(218, 110);
        output.WriteString(OnlineReplayDownloadUrl);
      }
      if (UseTcp != false) {
        output.WriteRawTag(224, 127);
        output.WriteBool(UseTcp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AssetBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetBundleVersionUpdateUrl);
      }
      if (StopBeginTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StopBeginTime);
      }
      if (DesignDataReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DesignDataReloginType);
      }
      if (LuaBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LuaBundleVersionUpdateUrl);
      }
      if (EnableDesignDataBundleVersionUpdate != false) {
        output.WriteRawTag(40);
        output.WriteBool(EnableDesignDataBundleVersionUpdate);
      }
      if (DesignDataBundleVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DesignDataBundleVersionUpdateUrl);
      }
      if (AsbReloginDesc.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AsbReloginDesc);
      }
      if (StopEndTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(StopEndTime);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (AsbReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        output.WriteRawTag(80);
        output.WriteEnum((int) AsbReloginType);
      }
      if (Port != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Port);
      }
      if (EnableAssetBundleVersionUpdate != false) {
        output.WriteRawTag(96);
        output.WriteBool(EnableAssetBundleVersionUpdate);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Host);
      }
      if (StopDesc.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StopDesc);
      }
      if (DispatchInfo != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success) {
        output.WriteRawTag(120);
        output.WriteEnum((int) DispatchInfo);
      }
      if (ServerUrlDict2.Length != 0) {
        output.WriteRawTag(186, 5);
        output.WriteString(ServerUrlDict2);
      }
      if (OnlineReplayUploadUrl.Length != 0) {
        output.WriteRawTag(226, 11);
        output.WriteString(OnlineReplayUploadUrl);
      }
      if (ServerUrlDict10.Length != 0) {
        output.WriteRawTag(138, 15);
        output.WriteString(ServerUrlDict10);
      }
      if (ServerDescription.Length != 0) {
        output.WriteRawTag(146, 15);
        output.WriteString(ServerDescription);
      }
      if (LuaPatchVersion.Length != 0) {
        output.WriteRawTag(242, 16);
        output.WriteString(LuaPatchVersion);
      }
      if (EnableSaveReplayFile != false) {
        output.WriteRawTag(144, 19);
        output.WriteBool(EnableSaveReplayFile);
      }
      if (ServerUrlDict7.Length != 0) {
        output.WriteRawTag(138, 24);
        output.WriteString(ServerUrlDict7);
      }
      if (EnableRedeemCode != false) {
        output.WriteRawTag(248, 25);
        output.WriteBool(EnableRedeemCode);
      }
      if (LoginWhiteMsg.Length != 0) {
        output.WriteRawTag(186, 29);
        output.WriteString(LoginWhiteMsg);
      }
      if (EventTrackingOpen != false) {
        output.WriteRawTag(168, 34);
        output.WriteBool(EventTrackingOpen);
      }
      if (ServerUrlDict4.Length != 0) {
        output.WriteRawTag(154, 41);
        output.WriteString(ServerUrlDict4);
      }
      if (MTPSwitch != false) {
        output.WriteRawTag(224, 42);
        output.WriteBool(MTPSwitch);
      }
      if (ServerUrlDict5.Length != 0) {
        output.WriteRawTag(130, 44);
        output.WriteString(ServerUrlDict5);
      }
      if (ServerUrlDict1.Length != 0) {
        output.WriteRawTag(170, 49);
        output.WriteString(ServerUrlDict1);
      }
      if (DesignDataReloginDesc.Length != 0) {
        output.WriteRawTag(242, 57);
        output.WriteString(DesignDataReloginDesc);
      }
      if (ServerUrlDict3.Length != 0) {
        output.WriteRawTag(218, 60);
        output.WriteString(ServerUrlDict3);
      }
      if (ServerUrlDict9.Length != 0) {
        output.WriteRawTag(226, 67);
        output.WriteString(ServerUrlDict9);
      }
      if (IOSExam != false) {
        output.WriteRawTag(216, 69);
        output.WriteBool(IOSExam);
      }
      if (PredownloadUpdateUrl.Length != 0) {
        output.WriteRawTag(226, 79);
        output.WriteString(PredownloadUpdateUrl);
      }
      if (EnableUploadBattleLog != false) {
        output.WriteRawTag(224, 83);
        output.WriteBool(EnableUploadBattleLog);
      }
      if (IFixPatchRevision.Length != 0) {
        output.WriteRawTag(250, 88);
        output.WriteString(IFixPatchRevision);
      }
      if (IFixPatchVersionUpdateUrl.Length != 0) {
        output.WriteRawTag(250, 91);
        output.WriteString(IFixPatchVersionUpdateUrl);
      }
      if (ServerUrlDict6.Length != 0) {
        output.WriteRawTag(138, 95);
        output.WriteString(ServerUrlDict6);
      }
      if (ForbidRecharge != false) {
        output.WriteRawTag(216, 103);
        output.WriteBool(ForbidRecharge);
      }
      if (ServerUrlDict8.Length != 0) {
        output.WriteRawTag(186, 109);
        output.WriteString(ServerUrlDict8);
      }
      if (OnlineReplayDownloadUrl.Length != 0) {
        output.WriteRawTag(218, 110);
        output.WriteString(OnlineReplayDownloadUrl);
      }
      if (UseTcp != false) {
        output.WriteRawTag(224, 127);
        output.WriteBool(UseTcp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AssetBundleVersionUpdateUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AssetBundleVersionUpdateUrl);
      }
      if (DesignDataReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DesignDataReloginType);
      }
      if (LuaBundleVersionUpdateUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaBundleVersionUpdateUrl);
      }
      if (EnableDesignDataBundleVersionUpdate != false) {
        size += 1 + 1;
      }
      if (DesignDataBundleVersionUpdateUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DesignDataBundleVersionUpdateUrl);
      }
      if (AsbReloginDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AsbReloginDesc);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (AsbReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AsbReloginType);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (EnableAssetBundleVersionUpdate != false) {
        size += 1 + 1;
      }
      if (Host.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
      }
      if (LuaPatchVersion.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(LuaPatchVersion);
      }
      if (LoginWhiteMsg.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(LoginWhiteMsg);
      }
      if (DesignDataReloginDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DesignDataReloginDesc);
      }
      if (PredownloadUpdateUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PredownloadUpdateUrl);
      }
      if (IFixPatchRevision.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IFixPatchRevision);
      }
      if (IFixPatchVersionUpdateUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IFixPatchVersionUpdateUrl);
      }
      if (StopBeginTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StopBeginTime);
      }
      if (StopEndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StopEndTime);
      }
      if (StopDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StopDesc);
      }
      if (ServerUrlDict1.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict1);
      }
      if (ServerUrlDict2.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict2);
      }
      if (ServerUrlDict3.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict3);
      }
      if (ServerUrlDict4.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict4);
      }
      if (ServerUrlDict5.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict5);
      }
      if (ServerUrlDict6.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict6);
      }
      if (ServerUrlDict7.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict7);
      }
      if (ServerUrlDict8.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict8);
      }
      if (ServerUrlDict9.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict9);
      }
      if (ServerUrlDict10.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerUrlDict10);
      }
      if (UseTcp != false) {
        size += 2 + 1;
      }
      if (EnableSaveReplayFile != false) {
        size += 2 + 1;
      }
      if (EnableUploadBattleLog != false) {
        size += 2 + 1;
      }
      if (ServerDescription.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerDescription);
      }
      if (OnlineReplayUploadUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(OnlineReplayUploadUrl);
      }
      if (OnlineReplayDownloadUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(OnlineReplayDownloadUrl);
      }
      if (EnableRedeemCode != false) {
        size += 2 + 1;
      }
      if (ForbidRecharge != false) {
        size += 2 + 1;
      }
      if (MTPSwitch != false) {
        size += 2 + 1;
      }
      if (EventTrackingOpen != false) {
        size += 2 + 1;
      }
      if (IOSExam != false) {
        size += 2 + 1;
      }
      if (DispatchInfo != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DispatchInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StarRailGateway other) {
      if (other == null) {
        return;
      }
      if (other.AssetBundleVersionUpdateUrl.Length != 0) {
        AssetBundleVersionUpdateUrl = other.AssetBundleVersionUpdateUrl;
      }
      if (other.DesignDataReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        DesignDataReloginType = other.DesignDataReloginType;
      }
      if (other.LuaBundleVersionUpdateUrl.Length != 0) {
        LuaBundleVersionUpdateUrl = other.LuaBundleVersionUpdateUrl;
      }
      if (other.EnableDesignDataBundleVersionUpdate != false) {
        EnableDesignDataBundleVersionUpdate = other.EnableDesignDataBundleVersionUpdate;
      }
      if (other.DesignDataBundleVersionUpdateUrl.Length != 0) {
        DesignDataBundleVersionUpdateUrl = other.DesignDataBundleVersionUpdateUrl;
      }
      if (other.AsbReloginDesc.Length != 0) {
        AsbReloginDesc = other.AsbReloginDesc;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.AsbReloginType != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode.NoKick) {
        AsbReloginType = other.AsbReloginType;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.EnableAssetBundleVersionUpdate != false) {
        EnableAssetBundleVersionUpdate = other.EnableAssetBundleVersionUpdate;
      }
      if (other.Host.Length != 0) {
        Host = other.Host;
      }
      if (other.LuaPatchVersion.Length != 0) {
        LuaPatchVersion = other.LuaPatchVersion;
      }
      if (other.LoginWhiteMsg.Length != 0) {
        LoginWhiteMsg = other.LoginWhiteMsg;
      }
      if (other.DesignDataReloginDesc.Length != 0) {
        DesignDataReloginDesc = other.DesignDataReloginDesc;
      }
      if (other.PredownloadUpdateUrl.Length != 0) {
        PredownloadUpdateUrl = other.PredownloadUpdateUrl;
      }
      if (other.IFixPatchRevision.Length != 0) {
        IFixPatchRevision = other.IFixPatchRevision;
      }
      if (other.IFixPatchVersionUpdateUrl.Length != 0) {
        IFixPatchVersionUpdateUrl = other.IFixPatchVersionUpdateUrl;
      }
      if (other.StopBeginTime != 0L) {
        StopBeginTime = other.StopBeginTime;
      }
      if (other.StopEndTime != 0L) {
        StopEndTime = other.StopEndTime;
      }
      if (other.StopDesc.Length != 0) {
        StopDesc = other.StopDesc;
      }
      if (other.ServerUrlDict1.Length != 0) {
        ServerUrlDict1 = other.ServerUrlDict1;
      }
      if (other.ServerUrlDict2.Length != 0) {
        ServerUrlDict2 = other.ServerUrlDict2;
      }
      if (other.ServerUrlDict3.Length != 0) {
        ServerUrlDict3 = other.ServerUrlDict3;
      }
      if (other.ServerUrlDict4.Length != 0) {
        ServerUrlDict4 = other.ServerUrlDict4;
      }
      if (other.ServerUrlDict5.Length != 0) {
        ServerUrlDict5 = other.ServerUrlDict5;
      }
      if (other.ServerUrlDict6.Length != 0) {
        ServerUrlDict6 = other.ServerUrlDict6;
      }
      if (other.ServerUrlDict7.Length != 0) {
        ServerUrlDict7 = other.ServerUrlDict7;
      }
      if (other.ServerUrlDict8.Length != 0) {
        ServerUrlDict8 = other.ServerUrlDict8;
      }
      if (other.ServerUrlDict9.Length != 0) {
        ServerUrlDict9 = other.ServerUrlDict9;
      }
      if (other.ServerUrlDict10.Length != 0) {
        ServerUrlDict10 = other.ServerUrlDict10;
      }
      if (other.UseTcp != false) {
        UseTcp = other.UseTcp;
      }
      if (other.EnableSaveReplayFile != false) {
        EnableSaveReplayFile = other.EnableSaveReplayFile;
      }
      if (other.EnableUploadBattleLog != false) {
        EnableUploadBattleLog = other.EnableUploadBattleLog;
      }
      if (other.ServerDescription.Length != 0) {
        ServerDescription = other.ServerDescription;
      }
      if (other.OnlineReplayUploadUrl.Length != 0) {
        OnlineReplayUploadUrl = other.OnlineReplayUploadUrl;
      }
      if (other.OnlineReplayDownloadUrl.Length != 0) {
        OnlineReplayDownloadUrl = other.OnlineReplayDownloadUrl;
      }
      if (other.EnableRedeemCode != false) {
        EnableRedeemCode = other.EnableRedeemCode;
      }
      if (other.ForbidRecharge != false) {
        ForbidRecharge = other.ForbidRecharge;
      }
      if (other.MTPSwitch != false) {
        MTPSwitch = other.MTPSwitch;
      }
      if (other.EventTrackingOpen != false) {
        EventTrackingOpen = other.EventTrackingOpen;
      }
      if (other.IOSExam != false) {
        IOSExam = other.IOSExam;
      }
      if (other.DispatchInfo != global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode.Success) {
        DispatchInfo = other.DispatchInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AssetBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 16: {
            StopBeginTime = input.ReadInt64();
            break;
          }
          case 24: {
            DesignDataReloginType = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode) input.ReadEnum();
            break;
          }
          case 34: {
            LuaBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 40: {
            EnableDesignDataBundleVersionUpdate = input.ReadBool();
            break;
          }
          case 50: {
            DesignDataBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 58: {
            AsbReloginDesc = input.ReadString();
            break;
          }
          case 64: {
            StopEndTime = input.ReadInt64();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 80: {
            AsbReloginType = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode) input.ReadEnum();
            break;
          }
          case 88: {
            Port = input.ReadUInt32();
            break;
          }
          case 96: {
            EnableAssetBundleVersionUpdate = input.ReadBool();
            break;
          }
          case 106: {
            Host = input.ReadString();
            break;
          }
          case 114: {
            StopDesc = input.ReadString();
            break;
          }
          case 120: {
            DispatchInfo = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode) input.ReadEnum();
            break;
          }
          case 698: {
            ServerUrlDict2 = input.ReadString();
            break;
          }
          case 1506: {
            OnlineReplayUploadUrl = input.ReadString();
            break;
          }
          case 1930: {
            ServerUrlDict10 = input.ReadString();
            break;
          }
          case 1938: {
            ServerDescription = input.ReadString();
            break;
          }
          case 2162: {
            LuaPatchVersion = input.ReadString();
            break;
          }
          case 2448: {
            EnableSaveReplayFile = input.ReadBool();
            break;
          }
          case 3082: {
            ServerUrlDict7 = input.ReadString();
            break;
          }
          case 3320: {
            EnableRedeemCode = input.ReadBool();
            break;
          }
          case 3770: {
            LoginWhiteMsg = input.ReadString();
            break;
          }
          case 4392: {
            EventTrackingOpen = input.ReadBool();
            break;
          }
          case 5274: {
            ServerUrlDict4 = input.ReadString();
            break;
          }
          case 5472: {
            MTPSwitch = input.ReadBool();
            break;
          }
          case 5634: {
            ServerUrlDict5 = input.ReadString();
            break;
          }
          case 6314: {
            ServerUrlDict1 = input.ReadString();
            break;
          }
          case 7410: {
            DesignDataReloginDesc = input.ReadString();
            break;
          }
          case 7770: {
            ServerUrlDict3 = input.ReadString();
            break;
          }
          case 8674: {
            ServerUrlDict9 = input.ReadString();
            break;
          }
          case 8920: {
            IOSExam = input.ReadBool();
            break;
          }
          case 10210: {
            PredownloadUpdateUrl = input.ReadString();
            break;
          }
          case 10720: {
            EnableUploadBattleLog = input.ReadBool();
            break;
          }
          case 11386: {
            IFixPatchRevision = input.ReadString();
            break;
          }
          case 11770: {
            IFixPatchVersionUpdateUrl = input.ReadString();
            break;
          }
          case 12170: {
            ServerUrlDict6 = input.ReadString();
            break;
          }
          case 13272: {
            ForbidRecharge = input.ReadBool();
            break;
          }
          case 14010: {
            ServerUrlDict8 = input.ReadString();
            break;
          }
          case 14170: {
            OnlineReplayDownloadUrl = input.ReadString();
            break;
          }
          case 16352: {
            UseTcp = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AssetBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 16: {
            StopBeginTime = input.ReadInt64();
            break;
          }
          case 24: {
            DesignDataReloginType = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode) input.ReadEnum();
            break;
          }
          case 34: {
            LuaBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 40: {
            EnableDesignDataBundleVersionUpdate = input.ReadBool();
            break;
          }
          case 50: {
            DesignDataBundleVersionUpdateUrl = input.ReadString();
            break;
          }
          case 58: {
            AsbReloginDesc = input.ReadString();
            break;
          }
          case 64: {
            StopEndTime = input.ReadInt64();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 80: {
            AsbReloginType = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ReloginTypeCode) input.ReadEnum();
            break;
          }
          case 88: {
            Port = input.ReadUInt32();
            break;
          }
          case 96: {
            EnableAssetBundleVersionUpdate = input.ReadBool();
            break;
          }
          case 106: {
            Host = input.ReadString();
            break;
          }
          case 114: {
            StopDesc = input.ReadString();
            break;
          }
          case 120: {
            DispatchInfo = (global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Types.ServerDispatchReturnCode) input.ReadEnum();
            break;
          }
          case 698: {
            ServerUrlDict2 = input.ReadString();
            break;
          }
          case 1506: {
            OnlineReplayUploadUrl = input.ReadString();
            break;
          }
          case 1930: {
            ServerUrlDict10 = input.ReadString();
            break;
          }
          case 1938: {
            ServerDescription = input.ReadString();
            break;
          }
          case 2162: {
            LuaPatchVersion = input.ReadString();
            break;
          }
          case 2448: {
            EnableSaveReplayFile = input.ReadBool();
            break;
          }
          case 3082: {
            ServerUrlDict7 = input.ReadString();
            break;
          }
          case 3320: {
            EnableRedeemCode = input.ReadBool();
            break;
          }
          case 3770: {
            LoginWhiteMsg = input.ReadString();
            break;
          }
          case 4392: {
            EventTrackingOpen = input.ReadBool();
            break;
          }
          case 5274: {
            ServerUrlDict4 = input.ReadString();
            break;
          }
          case 5472: {
            MTPSwitch = input.ReadBool();
            break;
          }
          case 5634: {
            ServerUrlDict5 = input.ReadString();
            break;
          }
          case 6314: {
            ServerUrlDict1 = input.ReadString();
            break;
          }
          case 7410: {
            DesignDataReloginDesc = input.ReadString();
            break;
          }
          case 7770: {
            ServerUrlDict3 = input.ReadString();
            break;
          }
          case 8674: {
            ServerUrlDict9 = input.ReadString();
            break;
          }
          case 8920: {
            IOSExam = input.ReadBool();
            break;
          }
          case 10210: {
            PredownloadUpdateUrl = input.ReadString();
            break;
          }
          case 10720: {
            EnableUploadBattleLog = input.ReadBool();
            break;
          }
          case 11386: {
            IFixPatchRevision = input.ReadString();
            break;
          }
          case 11770: {
            IFixPatchVersionUpdateUrl = input.ReadString();
            break;
          }
          case 12170: {
            ServerUrlDict6 = input.ReadString();
            break;
          }
          case 13272: {
            ForbidRecharge = input.ReadBool();
            break;
          }
          case 14010: {
            ServerUrlDict8 = input.ReadString();
            break;
          }
          case 14170: {
            OnlineReplayDownloadUrl = input.ReadString();
            break;
          }
          case 16352: {
            UseTcp = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the StarRailGateway message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ServerDispatchReturnCode {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("Failure")] Failure = 1,
        [pbr::OriginalName("ServerStop")] ServerStop = 2,
        [pbr::OriginalName("VersionError")] VersionError = 3,
        [pbr::OriginalName("RET_FORCE_UPDATE")] RetForceUpdate = 4,
        [pbr::OriginalName("RET_LANGUAGE_ERROR")] RetLanguageError = 5,
        [pbr::OriginalName("RET_PLATFORM_ERROR")] RetPlatformError = 6,
        [pbr::OriginalName("RET_CDN_ERROR")] RetCdnError = 7,
      }

      public enum ReloginTypeCode {
        [pbr::OriginalName("NoKick")] NoKick = 0,
        [pbr::OriginalName("ForceKick")] ForceKick = 1,
        [pbr::OriginalName("IdleKick")] IdleKick = 2,
        [pbr::OriginalName("Silence")] Silence = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
