// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StarRailGateway.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hi3Helper.EncTool.Proto.StarRail {

  /// <summary>Holder for reflection information generated from StarRailGateway.proto</summary>
  public static partial class StarRailGatewayReflection {

    #region Descriptor
    /// <summary>File descriptor for StarRailGateway.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StarRailGatewayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTdGFyUmFpbEdhdGV3YXkucHJvdG8SIEhpM0hlbHBlci5FbmNUb29sLlBy",
            "b3RvLlN0YXJSYWlsIo4DCg9TdGFyUmFpbEdhdGV3YXkSDAoEVU5LMRgLIAEo",
            "DRIMCgRVTksyGA8gASgNEg0KBFVOSzMYmQYgASgNEhkKEVJlcG9EZXNpZ25E",
            "YXRhVVJMGAEgASgJEhIKClJlcG9Bc2JVUkwYAyABKAkSEgoKUmVwb0x1YVVS",
            "TBgGIAEoCRIWCg1SZXBvSG90Zml4VVJMGKoEIAEoCRIYCg9SZXBvcnRSZXBs",
            "YXlVUkwY/wQgASgJEh4KFVJlcG9ydFJlcGxheVVwbG9hZFVSTBjRBSABKAkS",
            "FQoNUHJvdG9TZXJ2ZXJJUBgIIAEoCRIXCg9Qcm90b1NlcnZlclBvcnQYCiAB",
            "KA0SFwoPUHJvdG9TZXJ2ZXJOYW1lGAwgASgJEhcKDlByb3RvU2VydmVyS2V5",
            "GO8GIAEoCRIUCgtGZWVkYmFja1VSTBibCCABKAkSEgoJU2Vzc2lvbklEGLoJ",
            "IAEoCRIXCg5TZXNzaW9uTWVzc2FnZRjrCSABKAkSFgoNU2Vzc2lvblJldHVy",
            "bhilCiABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway), global::Hi3Helper.EncTool.Proto.StarRail.StarRailGateway.Parser, new[]{ "UNK1", "UNK2", "UNK3", "RepoDesignDataURL", "RepoAsbURL", "RepoLuaURL", "RepoHotfixURL", "ReportReplayURL", "ReportReplayUploadURL", "ProtoServerIP", "ProtoServerPort", "ProtoServerName", "ProtoServerKey", "FeedbackURL", "SessionID", "SessionMessage", "SessionReturn" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StarRailGateway : pb::IMessage<StarRailGateway>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StarRailGateway> _parser = new pb::MessageParser<StarRailGateway>(() => new StarRailGateway());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StarRailGateway> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.EncTool.Proto.StarRail.StarRailGatewayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway(StarRailGateway other) : this() {
      uNK1_ = other.uNK1_;
      uNK2_ = other.uNK2_;
      uNK3_ = other.uNK3_;
      repoDesignDataURL_ = other.repoDesignDataURL_;
      repoAsbURL_ = other.repoAsbURL_;
      repoLuaURL_ = other.repoLuaURL_;
      repoHotfixURL_ = other.repoHotfixURL_;
      reportReplayURL_ = other.reportReplayURL_;
      reportReplayUploadURL_ = other.reportReplayUploadURL_;
      protoServerIP_ = other.protoServerIP_;
      protoServerPort_ = other.protoServerPort_;
      protoServerName_ = other.protoServerName_;
      protoServerKey_ = other.protoServerKey_;
      feedbackURL_ = other.feedbackURL_;
      sessionID_ = other.sessionID_;
      sessionMessage_ = other.sessionMessage_;
      sessionReturn_ = other.sessionReturn_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarRailGateway Clone() {
      return new StarRailGateway(this);
    }

    /// <summary>Field number for the "UNK1" field.</summary>
    public const int UNK1FieldNumber = 11;
    private uint uNK1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UNK1 {
      get { return uNK1_; }
      set {
        uNK1_ = value;
      }
    }

    /// <summary>Field number for the "UNK2" field.</summary>
    public const int UNK2FieldNumber = 15;
    private uint uNK2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UNK2 {
      get { return uNK2_; }
      set {
        uNK2_ = value;
      }
    }

    /// <summary>Field number for the "UNK3" field.</summary>
    public const int UNK3FieldNumber = 793;
    private uint uNK3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UNK3 {
      get { return uNK3_; }
      set {
        uNK3_ = value;
      }
    }

    /// <summary>Field number for the "RepoDesignDataURL" field.</summary>
    public const int RepoDesignDataURLFieldNumber = 1;
    private string repoDesignDataURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepoDesignDataURL {
      get { return repoDesignDataURL_; }
      set {
        repoDesignDataURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RepoAsbURL" field.</summary>
    public const int RepoAsbURLFieldNumber = 3;
    private string repoAsbURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepoAsbURL {
      get { return repoAsbURL_; }
      set {
        repoAsbURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RepoLuaURL" field.</summary>
    public const int RepoLuaURLFieldNumber = 6;
    private string repoLuaURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepoLuaURL {
      get { return repoLuaURL_; }
      set {
        repoLuaURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RepoHotfixURL" field.</summary>
    public const int RepoHotfixURLFieldNumber = 554;
    private string repoHotfixURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepoHotfixURL {
      get { return repoHotfixURL_; }
      set {
        repoHotfixURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ReportReplayURL" field.</summary>
    public const int ReportReplayURLFieldNumber = 639;
    private string reportReplayURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReportReplayURL {
      get { return reportReplayURL_; }
      set {
        reportReplayURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ReportReplayUploadURL" field.</summary>
    public const int ReportReplayUploadURLFieldNumber = 721;
    private string reportReplayUploadURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReportReplayUploadURL {
      get { return reportReplayUploadURL_; }
      set {
        reportReplayUploadURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProtoServerIP" field.</summary>
    public const int ProtoServerIPFieldNumber = 8;
    private string protoServerIP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProtoServerIP {
      get { return protoServerIP_; }
      set {
        protoServerIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProtoServerPort" field.</summary>
    public const int ProtoServerPortFieldNumber = 10;
    private uint protoServerPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtoServerPort {
      get { return protoServerPort_; }
      set {
        protoServerPort_ = value;
      }
    }

    /// <summary>Field number for the "ProtoServerName" field.</summary>
    public const int ProtoServerNameFieldNumber = 12;
    private string protoServerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProtoServerName {
      get { return protoServerName_; }
      set {
        protoServerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProtoServerKey" field.</summary>
    public const int ProtoServerKeyFieldNumber = 879;
    private string protoServerKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProtoServerKey {
      get { return protoServerKey_; }
      set {
        protoServerKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FeedbackURL" field.</summary>
    public const int FeedbackURLFieldNumber = 1051;
    private string feedbackURL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FeedbackURL {
      get { return feedbackURL_; }
      set {
        feedbackURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SessionID" field.</summary>
    public const int SessionIDFieldNumber = 1210;
    private string sessionID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionID {
      get { return sessionID_; }
      set {
        sessionID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SessionMessage" field.</summary>
    public const int SessionMessageFieldNumber = 1259;
    private string sessionMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionMessage {
      get { return sessionMessage_; }
      set {
        sessionMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SessionReturn" field.</summary>
    public const int SessionReturnFieldNumber = 1317;
    private string sessionReturn_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionReturn {
      get { return sessionReturn_; }
      set {
        sessionReturn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StarRailGateway);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StarRailGateway other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UNK1 != other.UNK1) return false;
      if (UNK2 != other.UNK2) return false;
      if (UNK3 != other.UNK3) return false;
      if (RepoDesignDataURL != other.RepoDesignDataURL) return false;
      if (RepoAsbURL != other.RepoAsbURL) return false;
      if (RepoLuaURL != other.RepoLuaURL) return false;
      if (RepoHotfixURL != other.RepoHotfixURL) return false;
      if (ReportReplayURL != other.ReportReplayURL) return false;
      if (ReportReplayUploadURL != other.ReportReplayUploadURL) return false;
      if (ProtoServerIP != other.ProtoServerIP) return false;
      if (ProtoServerPort != other.ProtoServerPort) return false;
      if (ProtoServerName != other.ProtoServerName) return false;
      if (ProtoServerKey != other.ProtoServerKey) return false;
      if (FeedbackURL != other.FeedbackURL) return false;
      if (SessionID != other.SessionID) return false;
      if (SessionMessage != other.SessionMessage) return false;
      if (SessionReturn != other.SessionReturn) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UNK1 != 0) hash ^= UNK1.GetHashCode();
      if (UNK2 != 0) hash ^= UNK2.GetHashCode();
      if (UNK3 != 0) hash ^= UNK3.GetHashCode();
      if (RepoDesignDataURL.Length != 0) hash ^= RepoDesignDataURL.GetHashCode();
      if (RepoAsbURL.Length != 0) hash ^= RepoAsbURL.GetHashCode();
      if (RepoLuaURL.Length != 0) hash ^= RepoLuaURL.GetHashCode();
      if (RepoHotfixURL.Length != 0) hash ^= RepoHotfixURL.GetHashCode();
      if (ReportReplayURL.Length != 0) hash ^= ReportReplayURL.GetHashCode();
      if (ReportReplayUploadURL.Length != 0) hash ^= ReportReplayUploadURL.GetHashCode();
      if (ProtoServerIP.Length != 0) hash ^= ProtoServerIP.GetHashCode();
      if (ProtoServerPort != 0) hash ^= ProtoServerPort.GetHashCode();
      if (ProtoServerName.Length != 0) hash ^= ProtoServerName.GetHashCode();
      if (ProtoServerKey.Length != 0) hash ^= ProtoServerKey.GetHashCode();
      if (FeedbackURL.Length != 0) hash ^= FeedbackURL.GetHashCode();
      if (SessionID.Length != 0) hash ^= SessionID.GetHashCode();
      if (SessionMessage.Length != 0) hash ^= SessionMessage.GetHashCode();
      if (SessionReturn.Length != 0) hash ^= SessionReturn.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RepoDesignDataURL.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RepoDesignDataURL);
      }
      if (RepoAsbURL.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepoAsbURL);
      }
      if (RepoLuaURL.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RepoLuaURL);
      }
      if (ProtoServerIP.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ProtoServerIP);
      }
      if (ProtoServerPort != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ProtoServerPort);
      }
      if (UNK1 != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UNK1);
      }
      if (ProtoServerName.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ProtoServerName);
      }
      if (UNK2 != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(UNK2);
      }
      if (RepoHotfixURL.Length != 0) {
        output.WriteRawTag(210, 34);
        output.WriteString(RepoHotfixURL);
      }
      if (ReportReplayURL.Length != 0) {
        output.WriteRawTag(250, 39);
        output.WriteString(ReportReplayURL);
      }
      if (ReportReplayUploadURL.Length != 0) {
        output.WriteRawTag(138, 45);
        output.WriteString(ReportReplayUploadURL);
      }
      if (UNK3 != 0) {
        output.WriteRawTag(200, 49);
        output.WriteUInt32(UNK3);
      }
      if (ProtoServerKey.Length != 0) {
        output.WriteRawTag(250, 54);
        output.WriteString(ProtoServerKey);
      }
      if (FeedbackURL.Length != 0) {
        output.WriteRawTag(218, 65);
        output.WriteString(FeedbackURL);
      }
      if (SessionID.Length != 0) {
        output.WriteRawTag(210, 75);
        output.WriteString(SessionID);
      }
      if (SessionMessage.Length != 0) {
        output.WriteRawTag(218, 78);
        output.WriteString(SessionMessage);
      }
      if (SessionReturn.Length != 0) {
        output.WriteRawTag(170, 82);
        output.WriteString(SessionReturn);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RepoDesignDataURL.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RepoDesignDataURL);
      }
      if (RepoAsbURL.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepoAsbURL);
      }
      if (RepoLuaURL.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RepoLuaURL);
      }
      if (ProtoServerIP.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ProtoServerIP);
      }
      if (ProtoServerPort != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ProtoServerPort);
      }
      if (UNK1 != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UNK1);
      }
      if (ProtoServerName.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ProtoServerName);
      }
      if (UNK2 != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(UNK2);
      }
      if (RepoHotfixURL.Length != 0) {
        output.WriteRawTag(210, 34);
        output.WriteString(RepoHotfixURL);
      }
      if (ReportReplayURL.Length != 0) {
        output.WriteRawTag(250, 39);
        output.WriteString(ReportReplayURL);
      }
      if (ReportReplayUploadURL.Length != 0) {
        output.WriteRawTag(138, 45);
        output.WriteString(ReportReplayUploadURL);
      }
      if (UNK3 != 0) {
        output.WriteRawTag(200, 49);
        output.WriteUInt32(UNK3);
      }
      if (ProtoServerKey.Length != 0) {
        output.WriteRawTag(250, 54);
        output.WriteString(ProtoServerKey);
      }
      if (FeedbackURL.Length != 0) {
        output.WriteRawTag(218, 65);
        output.WriteString(FeedbackURL);
      }
      if (SessionID.Length != 0) {
        output.WriteRawTag(210, 75);
        output.WriteString(SessionID);
      }
      if (SessionMessage.Length != 0) {
        output.WriteRawTag(218, 78);
        output.WriteString(SessionMessage);
      }
      if (SessionReturn.Length != 0) {
        output.WriteRawTag(170, 82);
        output.WriteString(SessionReturn);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UNK1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UNK1);
      }
      if (UNK2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UNK2);
      }
      if (UNK3 != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(UNK3);
      }
      if (RepoDesignDataURL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoDesignDataURL);
      }
      if (RepoAsbURL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoAsbURL);
      }
      if (RepoLuaURL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoLuaURL);
      }
      if (RepoHotfixURL.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(RepoHotfixURL);
      }
      if (ReportReplayURL.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ReportReplayURL);
      }
      if (ReportReplayUploadURL.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ReportReplayUploadURL);
      }
      if (ProtoServerIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProtoServerIP);
      }
      if (ProtoServerPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtoServerPort);
      }
      if (ProtoServerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProtoServerName);
      }
      if (ProtoServerKey.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ProtoServerKey);
      }
      if (FeedbackURL.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(FeedbackURL);
      }
      if (SessionID.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SessionID);
      }
      if (SessionMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SessionMessage);
      }
      if (SessionReturn.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SessionReturn);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StarRailGateway other) {
      if (other == null) {
        return;
      }
      if (other.UNK1 != 0) {
        UNK1 = other.UNK1;
      }
      if (other.UNK2 != 0) {
        UNK2 = other.UNK2;
      }
      if (other.UNK3 != 0) {
        UNK3 = other.UNK3;
      }
      if (other.RepoDesignDataURL.Length != 0) {
        RepoDesignDataURL = other.RepoDesignDataURL;
      }
      if (other.RepoAsbURL.Length != 0) {
        RepoAsbURL = other.RepoAsbURL;
      }
      if (other.RepoLuaURL.Length != 0) {
        RepoLuaURL = other.RepoLuaURL;
      }
      if (other.RepoHotfixURL.Length != 0) {
        RepoHotfixURL = other.RepoHotfixURL;
      }
      if (other.ReportReplayURL.Length != 0) {
        ReportReplayURL = other.ReportReplayURL;
      }
      if (other.ReportReplayUploadURL.Length != 0) {
        ReportReplayUploadURL = other.ReportReplayUploadURL;
      }
      if (other.ProtoServerIP.Length != 0) {
        ProtoServerIP = other.ProtoServerIP;
      }
      if (other.ProtoServerPort != 0) {
        ProtoServerPort = other.ProtoServerPort;
      }
      if (other.ProtoServerName.Length != 0) {
        ProtoServerName = other.ProtoServerName;
      }
      if (other.ProtoServerKey.Length != 0) {
        ProtoServerKey = other.ProtoServerKey;
      }
      if (other.FeedbackURL.Length != 0) {
        FeedbackURL = other.FeedbackURL;
      }
      if (other.SessionID.Length != 0) {
        SessionID = other.SessionID;
      }
      if (other.SessionMessage.Length != 0) {
        SessionMessage = other.SessionMessage;
      }
      if (other.SessionReturn.Length != 0) {
        SessionReturn = other.SessionReturn;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RepoDesignDataURL = input.ReadString();
            break;
          }
          case 26: {
            RepoAsbURL = input.ReadString();
            break;
          }
          case 50: {
            RepoLuaURL = input.ReadString();
            break;
          }
          case 66: {
            ProtoServerIP = input.ReadString();
            break;
          }
          case 80: {
            ProtoServerPort = input.ReadUInt32();
            break;
          }
          case 88: {
            UNK1 = input.ReadUInt32();
            break;
          }
          case 98: {
            ProtoServerName = input.ReadString();
            break;
          }
          case 120: {
            UNK2 = input.ReadUInt32();
            break;
          }
          case 4434: {
            RepoHotfixURL = input.ReadString();
            break;
          }
          case 5114: {
            ReportReplayURL = input.ReadString();
            break;
          }
          case 5770: {
            ReportReplayUploadURL = input.ReadString();
            break;
          }
          case 6344: {
            UNK3 = input.ReadUInt32();
            break;
          }
          case 7034: {
            ProtoServerKey = input.ReadString();
            break;
          }
          case 8410: {
            FeedbackURL = input.ReadString();
            break;
          }
          case 9682: {
            SessionID = input.ReadString();
            break;
          }
          case 10074: {
            SessionMessage = input.ReadString();
            break;
          }
          case 10538: {
            SessionReturn = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RepoDesignDataURL = input.ReadString();
            break;
          }
          case 26: {
            RepoAsbURL = input.ReadString();
            break;
          }
          case 50: {
            RepoLuaURL = input.ReadString();
            break;
          }
          case 66: {
            ProtoServerIP = input.ReadString();
            break;
          }
          case 80: {
            ProtoServerPort = input.ReadUInt32();
            break;
          }
          case 88: {
            UNK1 = input.ReadUInt32();
            break;
          }
          case 98: {
            ProtoServerName = input.ReadString();
            break;
          }
          case 120: {
            UNK2 = input.ReadUInt32();
            break;
          }
          case 4434: {
            RepoHotfixURL = input.ReadString();
            break;
          }
          case 5114: {
            ReportReplayURL = input.ReadString();
            break;
          }
          case 5770: {
            ReportReplayUploadURL = input.ReadString();
            break;
          }
          case 6344: {
            UNK3 = input.ReadUInt32();
            break;
          }
          case 7034: {
            ProtoServerKey = input.ReadString();
            break;
          }
          case 8410: {
            FeedbackURL = input.ReadString();
            break;
          }
          case 9682: {
            SessionID = input.ReadString();
            break;
          }
          case 10074: {
            SessionMessage = input.ReadString();
            break;
          }
          case 10538: {
            SessionReturn = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
